// --- ÖĞRETMEN / MASTER GİRİŞİ ---
const ADMIN_HESABI = { ad: "Murat Mutlu", no: "1310" };

// --- 10. SINIF GÜVENLİK BEYAZ LİSTESİ (224 Öğrenci) ---
const KAYITLI_OGRENCILER = [
    // 10-A
    { ad: "MUHAMMED YUSUF KAYA", no: "6" },
    { ad: "ENSAR ATSIZ", no: "24" },
    { ad: "YUSUF GÜL", no: "112" },
    { ad: "MİHRAÇ AKKUL", no: "157" },
    { ad: "MUHAMMED ALİ BİLİK", no: "174" },
    { ad: "İSMAİL OZAT", no: "226" },
    { ad: "AHMET ŞÜKRÜ BAYLAN", no: "265" },
    { ad: "MUSTAFA PEYÇİ", no: "272" },
    { ad: "OSMAN SERTKAYA", no: "296" },
    { ad: "MUHAMMED KAHRAMAN", no: "318" },
    { ad: "ESAT KAPLAN", no: "336" },
    { ad: "MUHAMMED BARAN OZAT", no: "382" },
    { ad: "MEHMET REŞİT ÖZDİL", no: "416" },
    { ad: "EMİRHAN YALÇIN", no: "425" },
    { ad: "ÖMER BOZKURT", no: "427" },
    { ad: "ARAFAT KURTEKİN", no: "430" },
    { ad: "MAHMUT KANTAR", no: "431" },
    { ad: "FATİH KAĞBA", no: "438" },
    { ad: "YUSUF NİLÜFER", no: "441" },
    { ad: "YASİN KAHRAMAN", no: "442" },
    { ad: "MURAT RODİ YILMAZ", no: "445" },
    { ad: "MUHAMMED ÜVEYS KILIÇ", no: "448" },
    { ad: "AZAT KAYIK", no: "453" },
    { ad: "MUHAMMED EMİR ÖZDİL", no: "460" },
    { ad: "MEDİNE ÇINAR", no: "608" },
    { ad: "HARUN SEVİM", no: "849" },
    { ad: "ABDULSELAM ERGİN", no: "854" },
    { ad: "ALİ İMRAN AKSOY", no: "2100" },
    { ad: "BÜNYAMİN YORULMAZ", no: "2101" },
    { ad: "EBUBEKİR ACAR", no: "2107" },
    // 10-B
    { ad: "MURAT BARAN", no: "140" },
    { ad: "MAHMUT KESKİN", no: "161" },
    { ad: "MAZLUM DOĞAN TAPKAN", no: "189" },
    { ad: "DELAL HOŞER", no: "201" },
    { ad: "GÜLİSTAN TATAR", no: "444" },
    { ad: "RIZA KAYA", no: "459" },
    { ad: "MUHAMMED BARAN DİKENYOL", no: "485" },
    { ad: "BERAT MUSTAFAOĞLU", no: "486" },
    { ad: "BÜNYAMİN ŞANLI", no: "487" },
    { ad: "ENGİN BABAT", no: "490" },
    { ad: "MURAT ÇETİNER", no: "491" },
    { ad: "YAKUP KESKİN", no: "493" },
    { ad: "CİVAN ABIK", no: "494" },
    { ad: "ENES UZUNBAY", no: "495" },
    { ad: "BERAT MEN", no: "506" },
    { ad: "ABDULSAMET KAPAR", no: "508" },
    { ad: "ERKAN AK", no: "516" },
    { ad: "YUSUF ARSOY", no: "535" },
    { ad: "MUHAMMED DEMİRDAĞ", no: "536" },
    { ad: "MUHAMMED MERT İMREN", no: "554" },
    { ad: "ENES ZİYA", no: "580" },
    { ad: "SERHAT BİLİR", no: "612" },
    { ad: "İSMET DUĞU", no: "639" },
    { ad: "TARIK EFE ÖZDEMİR", no: "697" },
    { ad: "BEYZA NUR GÜL", no: "784" },
    { ad: "BERAT HÜSEYİN KAYA", no: "811" },
    { ad: "MUSA EKİNCİ", no: "813" },
    { ad: "SAMİ YUSUF EMUN", no: "843" },
    { ad: "MUHAMMED ABAN", no: "853" },
    // 10-C
    { ad: "MUHAMMED ENES SALA", no: "264" },
    { ad: "BÜNYAMİN ORHAN", no: "525" },
    { ad: "MUSTAFA BOĞUŞ", no: "533" },
    { ad: "MUHAMMED ENES ÇELİK", no: "534" },
    { ad: "FIRAT AVCI", no: "537" },
    { ad: "VEYSİ ERENG", no: "540" },
    { ad: "YUSUF YAKUT", no: "541" },
    { ad: "İSHAK ÇAKAR", no: "542" },
    { ad: "MUHAMMED İKBAL EREN", no: "547" },
    { ad: "MAZLUM KARDAŞ", no: "548" },
    { ad: "FERIT GÖNÜL", no: "558" },
    { ad: "MUHAMMED EKİNCİ", no: "560" },
    { ad: "MUHAMMED ENES EKİNCİ", no: "561" },
    { ad: "MUHAMMED ÖZ", no: "563" },
    { ad: "ÖZCAN TEYMUR", no: "568" },
    { ad: "MEHMET YASİN KANAT", no: "569" },
    { ad: "YAKUP AYANA", no: "574" },
    { ad: "MUHAMMED MUSA SOYSAL", no: "582" },
    { ad: "TAHA DİLDİRİM", no: "585" },
    { ad: "MUSTAFA CANSAĞ", no: "587" },
    { ad: "BİLAL YURDEM", no: "588" },
    { ad: "MUHAMMED EMRE EKİNCİ", no: "654" },
    { ad: "İLAYDA ALAN", no: "672" },
    { ad: "KENDAL ERDEM", no: "699" },
    { ad: "İLKNUR EKİN", no: "715" },
    { ad: "YAĞMUR ACU", no: "723" },
    // 10-D
    { ad: "HAMZA TURAL", no: "26" },
    { ad: "YUSUF DİCLE", no: "120" },
    { ad: "MEHMET ALİ AZAD BIÇAKÇI", no: "133" },
    { ad: "EMİN CAN İLTEN", no: "278" },
    { ad: "SADIK COBAN", no: "308" },
    { ad: "YUSUF KOYUNCU", no: "424" },
    { ad: "VİYAN KOYUNCU", no: "462" },
    { ad: "KÜBRA ALTUN", no: "469" },
    { ad: "MUHAMMED MUSTAFA İNALCAN", no: "470" },
    { ad: "RAVAN ELKANATIRİ", no: "478" },
    { ad: "BATUHAN FIRAT KÖYLÜ", no: "513" },
    { ad: "CEMRE ÇİLE", no: "526" },
    { ad: "OZAN YAĞUZLUK", no: "539" },
    { ad: "OSMAN CAN", no: "543" },
    { ad: "YASİR İLERİ", no: "578" },
    { ad: "ECRİN BARIŞ", no: "603" },
    { ad: "VEYSEL GÜNEŞ", no: "613" },
    { ad: "MAHMUT SİNCAR", no: "652" },
    { ad: "FIRAT GUNAY", no: "666" },
    { ad: "SANİYE AZRA İNANÇ", no: "704" },
    { ad: "ALİ OKAN", no: "720" },
    { ad: "İSA OKAN", no: "721" },
    { ad: "ABDULSAMET SEZGİN", no: "735" },
    { ad: "SÜMEYE GÜNEŞ", no: "761" },
    { ad: "HARUN KILIÇ", no: "765" },
    { ad: "ÜMRA BAYHAN", no: "963" },
    { ad: "AHMET OKAN CANBEYOĞLU", no: "2071" },
    { ad: "İBRAHİM BARIŞ GEZER", no: "2075" },
    // 10-E
    { ad: "MUHAMMED EMİN DİLEGİL", no: "58" },
    { ad: "İBRAHİM HALİL KARDAŞ", no: "61" },
    { ad: "MUHAMMED ENSAR DOĞAN", no: "253" },
    { ad: "MUHAMMED SAID ORAN", no: "294" },
    { ad: "MAHMUT AMİR ÖNDER", no: "299" },
    { ad: "ABDULLAH YUSUF GÜÇİN", no: "333" },
    { ad: "YUSUF GÜMÜŞ", no: "458" },
    { ad: "MUHAMMED HAMZA ATUĞ", no: "604" },
    { ad: "FURKAN ÇINAR", no: "611" },
    { ad: "ALEYNA KOC", no: "614" },
    { ad: "AHMED TUZUN", no: "627" },
    { ad: "MUHAMMED YASİR ÇAĞİNE", no: "658" },
    { ad: "OSMAN BOĞA", no: "659" },
    { ad: "FURKAN ERNEKAL", no: "668" },
    { ad: "HAMZA BULAT", no: "673" },
    { ad: "MUHAMMED BEDRAN ÖZPERK", no: "677" },
    { ad: "MERDA SARIGÖL", no: "682" },
    { ad: "YELDA SARIGÖL", no: "683" },
    { ad: "AHMET KARTAL", no: "684" },
    { ad: "ÖMER FARUK TANIK", no: "691" },
    { ad: "UMUT SAYHAN", no: "693" },
    { ad: "FESİH GÖNÜL", no: "706" },
    { ad: "MELEK GÜZHAN", no: "717" },
    { ad: "EMRULLAH AKSOY", no: "2109" },
    { ad: "MUHAMMED BUHARİ BİÇEN", no: "2116" },
    { ad: "SEMİH AKSOY", no: "2130" },
    // 10-F
    { ad: "VEYSEL BURAK ÇELİK", no: "4" },
    { ad: "İBRAHİM DEMİRTAŞ", no: "69" },
    { ad: "KEREM SEVEN", no: "234" },
    { ad: "YAĞMUR KANTAR", no: "268" },
    { ad: "MİRAN CANER ÖZTOPRAK", no: "591" },
    { ad: "MEHMET RÜZGAR ŞİMŞEK", no: "599" },
    { ad: "SÜLEYMAN CENS", no: "676" },
    { ad: "EMRE KAYA", no: "701" },
    { ad: "YASİN BIKMAZ", no: "718" },
    { ad: "SUAT ETİKE", no: "727" },
    { ad: "MUHAMMED ENES DİKENYOL", no: "729" },
    { ad: "RIZA ÇAĞ", no: "733" },
    { ad: "HASAN TÜRK", no: "736" },
    { ad: "MUHAMMED MUSTAFA HÜSNÜOĞLU", no: "737" },
    { ad: "LOKMAN ACAR", no: "742" },
    { ad: "MUHAMMED SEFA TUNÇ", no: "751" },
    { ad: "TURGUT KAYA", no: "753" },
    { ad: "MUHAMMED EMİR BARLAK", no: "755" },
    { ad: "MUHAMMED OYGO", no: "756" },
    { ad: "ERSİN AKKUŞ", no: "758" },
    { ad: "ONUR TİRKİ", no: "764" },
    { ad: "İSLAM ÖMER PEKİNCE", no: "767" },
    { ad: "MUSTAFA ÇÜÇÜN", no: "768" },
    { ad: "PINAR ASLANTAŞ", no: "797" },
    { ad: "ÜLKÜ ÇELİK", no: "807" },
    { ad: "OZAN ŞANLI", no: "995" },
    { ad: "EMRULLAH BİLTEKİN", no: "2105" },
    { ad: "ESENGÜL ARSLAN", no: "2108" },
    // 10-G
    { ad: "CESUR KELEŞ", no: "109" },
    { ad: "KADİR TUNG", no: "195" },
    { ad: "HASAN INAÇ", no: "213" },
    { ad: "YUSUF EROĞLU", no: "249" },
    { ad: "SEVİM YAMAN", no: "292" },
    { ad: "ENES BATIN", no: "409" },
    { ad: "ISMAN ACAR", no: "562" },
    { ad: "BARAN KARABULUT", no: "671" },
    { ad: "MUHAMMED VEYSEL TEKİN", no: "773" },
    { ad: "YUSUF KÜSECE", no: "777" },
    { ad: "SERKAN USLU", no: "779" },
    { ad: "MUHAMMED YUSUF AKTAR", no: "782" },
    { ad: "ARDA DOĞMUŞ", no: "787" },
    { ad: "YASİN FİREĞAR", no: "791" },
    { ad: "VEYSEL OTANÇ", no: "799" },
    { ad: "ŞEHMUS DURMAZ", no: "801" },
    { ad: "EMİRHAN EBİNÇ", no: "803" },
    { ad: "BATUHAN SAĞIR", no: "805" },
    { ad: "İSA BURUN", no: "808" },
    { ad: "İSMAİL KAYA", no: "821" },
    { ad: "İREM NUR ARLI", no: "1000" },
    { ad: "SABRİ YAMAN", no: "2060" },
    { ad: "DOĞAN AYDIN", no: "2074" },
    { ad: "BÜNYAMİN DEMİR", no: "2101" },
    { ad: "YUSUF İSLAM DOĞAN", no: "2104" },
    { ad: "ÖMER FARUK ACAR", no: "2117" },
    { ad: "VİYAN KESER", no: "2123" },
    { ad: "YUSUF ÖZTAŞ", no: "2125" },
    { ad: "YUSUF TAŞKESEN", no: "2126" },
    { ad: "MUHAMMED EMRE ASLAN", no: "2335" },
    // 10-H
    { ad: "NEJDET İNANÇ", no: "113" },
    { ad: "NEÇİRVAN KARAKUŞ", no: "428" },
    { ad: "MUHAMMED ALI ULUDAĞ", no: "497" },
    { ad: "BARAN AVCİ", no: "523" },
    { ad: "MUHAMMED ŞEN", no: "555" },
    { ad: "VEYSEL ÖZDEN", no: "594" },
    { ad: "ABDULLAH ŞARLAT", no: "688" },
    { ad: "ALİ BİLAL AYIŞ", no: "752" },
    { ad: "FATMA NUR TAŞ", no: "820" },
    { ad: "ŞERZAN DOĞAN", no: "822" },
    { ad: "VEYSEL YARAR", no: "823" },
    { ad: "MERHAMET EYLE ZARIÇ", no: "827" },
    { ad: "BERAT ÇİLE", no: "828" },
    { ad: "MUHAMMED EMİR KANSU", no: "829" },
    { ad: "UMUT CAN KINGIR", no: "830" },
    { ad: "EYYÜP AYDIN", no: "831" },
    { ad: "ÖMER FARUK ASLAN", no: "833" },
    { ad: "NEBİ EKBER ERİG", no: "835" },
    { ad: "NERGİZ ÖZGÜN", no: "840" },
    { ad: "ABDURRAHMAN OĞUZ", no: "850" },
    { ad: "MAHSUM UĞUR", no: "855" },
    { ad: "MUHAMMET PAZAN", no: "873" },
    { ad: "OMER BAĞDU", no: "875" },
    { ad: "HARUN ÇAĞİNE", no: "2072" },
    { ad: "AYŞE ADIYAMAN", no: "2073" },
    { ad: "MEHMET VELİ AKSOY", no: "2115" },
    { ad: "MUHAMMED MUSTAFA ACAR", no: "2135" },
    { ad: "HASAN GÜL", no: "2599" }
];