// ==========================================
// 9. SINIF İÇERİK VE SORU HAVUZU (TAM SÜRÜM)
// ==========================================

// --- 1. KAVRAMLAR SÖZLÜĞÜ (153 KAVRAM) ---
const KAVRAMLAR = [
    { terim: "Ağırşak", anlam: "Yün veya iplik eğrilen iği ağırlaştırmak için alt ucuna geçirilen yarım küre biçiminde, ortası delik ağaç veya kemik parça." },
    { terim: "Aidiyet", anlam: "Bir şeye ait olma durumu, aitlik." },
    { terim: "Aman Dilemek", anlam: "Önce direnirken zor karşısında boyun eğip canının bağışlanmasını dilemek." },
    { terim: "Amfora", anlam: "İki kulplu, dibi sivri, dar boyunlu, karnı geniş testi." },
    { terim: "Amil", anlam: "İslam halifeleri, hükümdarları ve emîrleri tarafından vergi toplamakla, idare işleriyle, valilikle görevlendirilen kimselere verilen bir unvan." },
    { terim: "Analiz Etmek", anlam: "Anlamı ve niteliği anlaşılamayan bir konuyu açıkladıktan sonra sonuca bağlamak, tahlil etmek." },
    { terim: "Analoji", anlam: "Bazı ortak yönleri bulunan iki şey arasındaki benzeşme, benzeşim." },
    { terim: "Anane", anlam: "Bir toplumda eskiden kalmış olmaları dolayısıyla saygın tutulup kuşaktan kuşağa iletilen, yaptırım gücü olan kültürel kalıntılar, alışkanlıklar, bilgi, töre ve davranışlar; gelenek, örf." },
    { terim: "Antik", anlam: "İlk Çağ’daki uygarlıklarla, özellikle eski Yunan ve Roma uygarlıkları ile ilgili olan." },
    { terim: "Antropoloji", anlam: "İnsanı hem biyolojik ve fiziksel özellikleriyle hem de toplumsal ve kültürel yönleriyle inceleyen bilim." },
    { terim: "Aristokrasi", anlam: "Soylular sınıfı." },
    { terim: "Arkaik", anlam: "Güzel sanatlarda klasik çağ öncesinden kalan; eskicil." },
    { terim: "Arma", anlam: "Bir devletin, bir hanedanın, bir sanayi kuruluşunun veya bir şehrin simgesi olarak kabul edilmiş resim, harf veya şekil; ongun." },
    { terim: "Arrade", anlam: "Muhasaralarda (kuşatmalarda) surları yıkmak için kullanılan savaş aracı, mancınık." },
    { terim: "Arşidük", anlam: "Avusturya’da imparator ailesi prenslerine verilen unvan." },
    { terim: "Aşık Kemiği", anlam: "Çift tırnaklı hayvanların ön dizlerinde bulunan bir eklem kemiği; aşık, kâp." },
    { terim: "Atıf Yapmak", anlam: "Bir başkasının daha önce yayımlanmış bir çalışmasına gönderme yapmak." },
    { terim: "Avam", anlam: "Sıradan insanlar, havas karşıtı." },
    { terim: "Balbal", anlam: "Eski Türklerde kişinin anılması için mezarının veya bazı kurganların etrafına dikilen taş." },
    { terim: "Balta", anlam: "Ağacı kesme, yarma, yontma vb. işlerde kullanılan ağaç saplı, demir araç." },
    { terim: "Başbuğ", anlam: "Eski Türklerde devletin veya ordunun başında olan kimse; Osmanlı Devleti’nde savaş zamanı milis güçlerinin komutanı." },
    { terim: "Bellek", anlam: "Yaşananları, öğrenilen konuları, bunların geçmişle ilişkisini bilinçli olarak zihinde saklama gücü; hafıza." },
    { terim: "Beşerî", anlam: "İnsanoğlu ile ilgili." },
    { terim: "Beytülmal", anlam: "Devletin hazinesi." },
    { terim: "Biat", anlam: "Bir kimsenin egemenliğini tanıma; bir hükümdarın hükmü altına girme." },
    { terim: "Bilim", anlam: "Evrenin veya olayların bir bölümünü konu olarak seçen, deneye dayanan yöntemler ve gerçeklikten yararlanarak sonuç çıkarmaya çalışan düzenli bilgi, ilim." },
    { terim: "Binaenaleyh", anlam: "Bundan dolayı, bunun için, bu açıdan." },
    { terim: "Birinci Elden Kaynaklar", anlam: "Olayların yaşandığı dönemde ya da bu dönemden hemen sonra oluşan veya oluşturulan özgün kaynaklar." },
    { terim: "Broş", anlam: "Yaka iğnesi." },
    { terim: "Büst", anlam: "Heykelcilikte başı, göğsü, bazen de omuzları içine alan sanat ürünü." },
    { terim: "Ceride", anlam: "Kayıt defteri." },
    { terim: "Coğrafya", anlam: "Yeryüzünü fiziki, ekonomik, beşerî ve siyasi yönlerden inceleyen bilim." },
    { terim: "Cumhuriyet", anlam: "Milletin, egemenliği kendi elinde tuttuğu ve bunu belirli süreler için seçtiği milletvekilleri aracılığıyla kullandığı yönetim biçimi." },
    { terim: "Cülus", anlam: "Hükümdarlık tahtına çıkma, tahta oturma." },
    { terim: "Çağ", anlam: "Kendine özgü bir özellik taşıyan zaman parçası; asır, dönem, devir." },
    { terim: "Çanak", anlam: "Toprak, metal vb. bir maddeden yapılmış yayvan, çukurca kap." },
    { terim: "Çapa", anlam: "Tarlalarda toprağı işlemek için kullanılan ağaç veya demir saplı kazı aracı." },
    { terim: "Çiftçi", anlam: "Geçimini toprağı ekerek sağlayan kimse." },
    { terim: "Çömlek", anlam: "Toprak tencere." },
    { terim: "Değişim ve Süreklilik", anlam: "Tarihin statik (durağan) olmadığını, toplumların ve yapıların zamanla farklılaştığını ancak bazı özelliklerin devam ettiğini ifade eden kavramlar." },
    { terim: "Devrim", anlam: "Belli bir alanda hızlı, köklü ve nitelikli değişiklik." },
    { terim: "Dikili Taş", anlam: "Önemli bir olayın durumu veya bir zaferin anısı için dikilmiş tek parça yüksek taş, obelisk." },
    { terim: "Dijital Doğuştan Kaynak (Born Digital)", anlam: "Genel ağ siteleri, e-kitaplar, elektronik kayıtlar gibi doğrudan dijital ortamda üretilen kaynaklar." },
    { terim: "Dijitalleşme", anlam: "Verilerin bilgisayar ortamında okunabilir hale getirilmesi ve işlenmesi süreci." },
    { terim: "Diplomatik", anlam: "Resmî belgeleri şekil ve içerik bakımından inceleyen bilim." },
    { terim: "Disiplin", anlam: "Bir topluluğun yasalarına ve kurallarına uyması durumu; öğretim konusu olan bilgi bütünü veya bilim dalı." },
    { terim: "Doğa Bilimleri", anlam: "Konusu tabiat olayları ve kanunları olan fizik, kimya, biyoloji vb. bilimler." },
    { terim: "Ecdat", anlam: "Geçmişteki büyükler, atalar." },
    { terim: "Edimsel", anlam: "Edim niteliğinde olan, gerçek olarak var olan; fiilî." },
    { terim: "Egemenlik", anlam: "Milletin ve devletin yetkilerinin hepsi; hâkimiyet." },
    { terim: "E-Kitap", anlam: "Bilgisayar, tablet, akıllı telefon gibi cihazlarda okunabilen etkileşimli kitap türü." },
    { terim: "Empati", anlam: "Aynı duyguları paylaşma, duygudaşlık." },
    { terim: "Epigrafi", anlam: "Kitabeleri ve üzerindeki yazıları şekil ve içerik bakımından inceleyen bilim." },
    { terim: "Etik", anlam: "Çeşitli meslek kolları arasında tarafların uyması gereken davranışlar bütünü." },
    { terim: "Etnografya", anlam: "Toplumların yaşayışlarını, hayat tarzlarını, örf ve âdetlerini inceleyen bilim." },
    { terim: "Evcilleştirmek", anlam: "Evcil bir duruma getirmek, ehlîleştirmek." },
    { terim: "Fey Geliri", anlam: "Savaş yapılmadan elde edilen ganimet." },
    { terim: "Filoloji", anlam: "Günümüzde ve geçmişte konuşulan dilleri ve bu dillerin gelişimlerini inceleyen bilim." },
    { terim: "Firari", anlam: "Kaçak, kaçkın." },
    { terim: "Firavun", anlam: "Eski Mısır hükümdarlarına verilen unvan." },
    { terim: "Fresk", anlam: "Yaş duvar sıvası üzerine kireç suyunda eritilmiş madenî boyalarla resim yapma yöntemi ve bu yöntemle yapılan duvar resmi." },
    { terim: "Geçmiş", anlam: "Yaşanmış ve değiştirilemez olayları ifade eden kavram." },
    { terim: "Genel Ağ (Web)", anlam: "Birbirine bağlantılı milyarlarca sayfadan oluşan bir hiper metin sistemi." },
    { terim: "Han", anlam: "Yolcuların konaklamalarına yarayan yapı." },
    { terim: "Hanedan", anlam: "Hükümdar soyu; belli ve köklü bir soydan gelen." },
    { terim: "Havza", anlam: "Sınırları idari, ekonomik birliğe veya coğrafi özelliklere göre belirlenen bölge." },
    { terim: "Hazine", anlam: "Büyük servet; devletin nakit işlemlerini düzenleyen makam." },
    { terim: "Heraldik", anlam: "Resmî belgelerdeki mühür, arma ve özel işaretleri inceleyen bilim." },
    { terim: "Heterojen", anlam: "Ayrı türden, ayrışık." },
    { terim: "Hiper Metin", anlam: "Birbiriyle bağlantılı yazı, görsel, video gibi verileri içeren bir metin organizasyonu." },
    { terim: "Hipodrom", anlam: "At ve araba yarışlarının yapıldığı yer." },
    { terim: "Hiyeroglif", anlam: "Antik Çağ’da Mısırlıların kullandığı resim yazısı." },
    { terim: "İkinci Elden Kaynaklar", anlam: "Olayların yaşanmasından sonra, birinci elden kaynaklara dayandırılarak ortaya konan eserler." },
    { terim: "İkta", anlam: "Devlete ait toprakların gelirlerinin asker veya sivil erkâna hizmet karşılığı verilmesi." },
    { terim: "İlkel", anlam: "Gelişmesinin başında bulunan, basit; zaman bakımından en eski olan." },
    { terim: "İllüstrasyon", anlam: "Kitap içindeki bir yazıyı açıklayan veya süsleyen resim." },
    { terim: "İmparatorluk", anlam: "Kendi topraklarında oturan çeşitli milletleri egemenliği altında toplayan devlet biçimi." },
    { terim: "İnşa Etmek", anlam: "Kurmak, yapmak (Tarihçiler geçmişi belgelerle yeniden inşa ederler)." },
    { terim: "Kabartma (Rölyef)", anlam: "Kil, taş vb. gereçleri girintili çıkıntılı yüzeyler durumunda biçimlendirerek yapılan eser." },
    { terim: "Kağan", anlam: "Hanların bağlı olduğu devlet başkanı." },
    { terim: "Kaide", anlam: "Kural; bir şeyin üzerine oturtulduğu tabanlık." },
    { terim: "Kanıt", anlam: "Tarihsel olay ve olguları destekleyen belgelerden ve kalıntılardan elde edilen veri." },
    { terim: "Kartograf", anlam: "Harita yapan kimse, haritacı." },
    { terim: "Kavim", anlam: "Aralarında töre, dil ve kültür ortaklığı bulunan insan topluluğu; budun." },
    { terim: "Kerpiç", anlam: "Saman ve balçık karışımı, güneşte kurutulmuş ilkel tuğla." },
    { terim: "Kervan", anlam: "Uzak yerlere yolcu ve ticaret eşyası taşıyan yük hayvanı katarı." },
    { terim: "Kimya", anlam: "Maddenin yapısını ve özelliklerini inceleyen, Karbon-14 yöntemiyle buluntuların yaşını belirlemeye yarayan bilim." },
    { terim: "Kıstas", anlam: "Ölçüt, kriter." },
    { terim: "Kompleks", anlam: "Karmaşık, içinde aynı cinsten birçok öge bulunan." },
    { terim: "Kompozit", anlam: "Karma; değişik tarzları bir arada taşıyan." },
    { terim: "Konargöçer", anlam: "Göçebe bir hayat süren, bir yere sürekli yerleşmeyen." },
    { terim: "Konik", anlam: "Koni biçiminde olan." },
    { terim: "Koşut", anlam: "Paralel, aynı zaman içinde gelişen." },
    { terim: "Köken", anlam: "Bir şeyin çıktığı, dayandığı temel; menşe." },
    { terim: "Kronik", anlam: "Günü gününe yazılmış olayları içine alan eser, vakayiname." },
    { terim: "Kronoloji", anlam: "Geçmişten günümüze meydana gelen olayları tarihlendirerek sıralayan zaman bilimi." },
    { terim: "Kurak", anlam: "Yağışı olmayan." },
    { terim: "Kurgan", anlam: "İlk Çağ’da mezar üzerine toprak yığılarak yapılan küçük tepe; tepe biçiminde mezar." },
    { terim: "Kurultay", anlam: "Eski Türklerde ve Moğollarda devlet işlerinin görüşülüp karara bağlandığı meclis." },
    { terim: "Levazım", anlam: "Ordunun ihtiyacı olan malzeme veya bu malzemeyi sağlayan bölüm." },
    { terim: "Lojistik", anlam: "Ordunun türlü gereksinimi ile ilgili işlerin bütünü, geri hizmet." },
    { terim: "Manipüle Etmek", anlam: "Yönlendirmek." },
    { terim: "Medeniyet", anlam: "Bir toplumun maddi ve manevi varlıklarının, fikir ve sanat çalışmalarının tümü; uygarlık." },
    { terim: "Meşruiyet", anlam: "Geçerli olma durumu, meşruluk." },
    { terim: "Metafor", anlam: "Bir kelimeyi kabul edilenin dışında başka anlamlara gelecek biçimde kullanma, mecaz." },
    { terim: "Mevali", anlam: "Azat edilmiş köleler (Emeviler döneminde Arap olmayan Müslümanlar için kullanılmıştır); Osmanlı'da yüksek dereceli ilim adamları." },
    { terim: "Minyatür", anlam: "Işık, gölge ve hacim duygusu yansıtılmayan küçük, renkli resim sanatı." },
    { terim: "Mitolojik", anlam: "Mitolojiyle ilgili, esatirî." },
    { terim: "Monarşi", anlam: "Siyasi otoritenin genellikle miras yolu ile bir kişinin üzerinde toplandığı devlet düzeni." },
    { terim: "Muhteva", anlam: "İçerik." },
    { terim: "Muvazzaf", anlam: "Silahlı Kuvvetlerde görev başında olan askerler; bir görevle yükümlü olan." },
    { terim: "Mükellef", anlam: "Yükümlü; eksiksiz yapılmış." },
    { terim: "Müstahkem", anlam: "Sağlamlaştırılmış, tahkim edilmiş." },
    { terim: "Müteferrik", anlam: "Birbirinden ayrılmış, dağılmış olan." },
    { terim: "Müteşekkil", anlam: "Oluşmuş, meydana gelmiş." },
    { terim: "Nalbant", anlam: "Hayvanların ayağına nal çakan kimse." },
    { terim: "Neden-Sonuç", anlam: "Tarihteki olay ve olgular arasındaki bağlantıları belirlemek için kullanılan kavram." },
    { terim: "Neolitik", anlam: "Taş Devri’nin son çağı (Cilalı Taş Devri) ile ilgili." },
    { terim: "Neşredilmek", anlam: "Yayımlanmak." },
    { terim: "Nizam", anlam: "Düzen, sistem." },
    { terim: "Nümismatik", anlam: "Eski para ve madalyaların tarihini ve tanımını inceleyen bilim." },
    { terim: "Obsidiyen", anlam: "Cam kaya, volkanik cam." },
    { terim: "Olay (Tarihî Olay)", anlam: "Belirli bir zaman diliminde meydana gelen, somut ve tarihî önem taşıyan gelişmeler (Örn: İstanbul'un Fethi)." },
    { terim: "Olgu (Tarihî Olgu)", anlam: "Olayların sonuçlarına dayanan, uzun süreli, soyut ve genel süreçler (Örn: Anadolu'nun Türkleşmesi)." },
    { terim: "Olgusal", anlam: "Olayların dayandığı sebep ve sonuçlarla ilgili olan." },
    { terim: "Orak", anlam: "Ekin, ot vb. biçme aracı." },
    { terim: "Özel Mülkiyet", anlam: "Kişinin sahip olduğu taşınır veya taşınmaz mal." },
    { terim: "Paleoantropolog", anlam: "İnsanın anatomik ve biyolojik değişimlerine odaklanan bilim insanı." },
    { terim: "Paleoantropoloji", anlam: "İnsanoğlunun anatomik ve biyolojik değişimlerini inceleyen bilim dalı." },
    { terim: "Paleografi", anlam: "Geçmişte kullanılan yazı çeşitlerini ve bu yazıların özelliklerini inceleyen bilim." },
    { terim: "Papirüs", anlam: "Eski Mısırlıların bir bitkinin saplarından yaptıkları kâğıt." },
    { terim: "Parşömen", anlam: "Yazı yazmak için özel olarak hazırlanan deri." },
    { terim: "Piramit", anlam: "Mısır firavunlarının anıt mezarı." },
    { terim: "Piroteknoloji", anlam: "Ateşin kontrollü kullanımı ve malzeme üretimindeki uygulamalarını inceleyen bilim dalı." },
    { terim: "Politeist", anlam: "Çok tanrılı din yanlısı." },
    { terim: "Reaya", anlam: "Bir hükümdarın yönetimi altındaki halk; Osmanlı'da vergi veren halk." },
    { terim: "Revizyon", anlam: "Yeniden gözden geçirip düzeltme." },
    { terim: "Rölyef", anlam: "Kabartma." },
    { terim: "Saban", anlam: "Çift süren hayvanların koşulduğu demir uçlu tarım aracı." },
    { terim: "Sarnıç", anlam: "Yağmur sularının biriktirildiği üstü kapalı yapı." },
    { terim: "Sav", anlam: "İleri sürülerek savunulan düşünce, tez." },
    { terim: "Senato", anlam: "Eski Roma’da yöneticiler meclisi." },
    { terim: "Sentezleme", anlam: "Fikirleri birleştirerek bir bütün hâline getirme." },
    { terim: "Skolastik", anlam: "Orta Çağ'da inanç ve bilgiyi kiliseyle birleştirmeye çalışan felsefe." },
    { terim: "Sosyoloji", anlam: "Toplumları ve toplumsal olayların neden ve etkilerini inceleyen bilim." },
    { terim: "Strateji", anlam: "Politik, ekonomik ve askerî güçleri bir arada kullanma bilimi ve sanatı." },
    { terim: "Sulak", anlam: "Suyu bol yer." },
    { terim: "Süreli Yayın", anlam: "Belirli aralıklarla yayımlanan dergi vb.." },
    { terim: "Şuur", anlam: "Bilinç." },
    { terim: "Şûra", anlam: "Danışma kurulu." },
    { terim: "Taarruz", anlam: "Saldırı." },
    { terim: "Tablet", anlam: "Üzerinde çivi yazısı ile metin yazılı kil belge." },
    { terim: "Tahıl", anlam: "Buğday, arpa, mısır vb. ürünlerin genel adı." },
    { terim: "Tahrir", anlam: "Yazma, kaydetme; tahrir defterleri." },
    { terim: "Takas", anlam: "Para kullanmadan mal değişimi." },
    { terim: "Taksimat", anlam: "Bölme, bölüştürme işleri." },
    { terim: "Tamga (Damga)", anlam: "Bir şeyin üzerine basılan nişan, işaret." },
    { terim: "Tanzim Etmek", anlam: "Düzenlemek." },
    { terim: "Tarih", anlam: "Geçmişteki insan faaliyetlerini, neden-sonuç ilişkisi içinde, yer ve zaman göstererek, belgelere dayalı olarak inceleyen bilim dalı." },
    { terim: "Tarihçi", anlam: "Geçmişi, günümüze ulaşan belgeler ve kanıtlarla yorumlayan ve yeniden inşa eden kişi." },
    { terim: "Tarih Öncesi (Prehistorya)", anlam: "Tarihin yazılı kaynaklardan öğrenilemeyen dönemleri." },
    { terim: "Tasarruf Etmek", anlam: "Bir malı istediği gibi kullanmak." },
    { terim: "Tasnif", anlam: "Sınıflama, ayırma." },
    { terim: "Tebaa", anlam: "Uyruk, vatanda." },
    { terim: "Teçhizat", anlam: "Donatı, savaş gereçleri." },
    { terim: "Teferruat", anlam: "Ayrıntı, detay." },
    { terim: "Tekemmül Etmek", anlam: "Olgunlaşmak, mükemmel duruma gelmek." },
    { terim: "Tenkit", anlam: "Eleştiri, bilginin doğruluğunu inceleme." },
    { terim: "Testi", anlam: "Geniş gövdeli, dar boğazlı su kabı." },
    { terim: "Topyekûn", anlam: "Eksiksiz, toplu olarak." },
    { terim: "Toy", anlam: "Türk hükümdarlarının verdiği büyük ziyafet, şölen." },
    { terim: "Töre", anlam: "Bir toplulukta benimsenmiş davranış, kural ve geleneklerin bütünü; yazısız hukuk." },
    { terim: "Turan", anlam: "Türklerin eski yurtları; dünyadaki Türkleri birleştirme ideali." },
    { terim: "Tüccar", anlam: "Ticaret yapan kimse." },
    { terim: "Vahim", anlam: "Ağır ve tehlikeli sonuç doğuracak olan." },
    { terim: "Vakıf", anlam: "Bir hizmetin yapılması için ayrılan mülk veya para." },
    { terim: "Vâris", anlam: "Mirasçı." },
    { terim: "Veraset", anlam: "Mirasta hak sahibi olma, kalıtım." },
    { terim: "Veri", anlam: "Bir araştırmanın temeli olan ana öge, data." },
    { terim: "Vesika", anlam: "Belge." },
    { terim: "Vuzuhsuz", anlam: "Belirsiz, niteliği tam bilinmeyen." },
    { terim: "Yalıtılmış", anlam: "İzole edilmiş." },
    { terim: "Yapay Zekâ", anlam: "Bilgisayarın veya robotun akıllı varlıklarla ilişkili görevleri yerine getirme yeteneği." },
    { terim: "Yazıt", anlam: "Bir şey üzerine kazılan yazı, kitabe." },
    { terim: "Yerleşik Hayat", anlam: "İnsanların tarımsal üretimle birlikte kalıcı konutlarda yaşamaya başlaması." },
    { terim: "Yörük", anlam: "Göçebe Türk oymağı." },
    { terim: "Yurt", anlam: "Vatan; göçebe Türk çadırı." },
    { terim: "Yüzyıl", anlam: "Milat başlangıç alınarak 100 yıllık dönemlere ayrılan zaman dilimi." },
    { terim: "Zahit", anlam: "Dinin yasaklarından sakınan, dünya işlerine önem vermeyen kimse." },
    { terim: "Zimmi", anlam: "İslam devleti idaresindeki gayrimüslim tebaa." }
];

// --- 2. DERS MATERYALLERİ (AKORDİYON MENÜ) ---
const dersMateryalleri = [
    {baslik: "📂 1. Ünite Ders Notları (PDF)", link: "materyaller/notlar/1_unite_notlari.pdf"},
    {baslik: "📂 2. Ünite Ders Notları (PDF)", link: "materyaller/notlar/2_unite_notlari.pdf"},
    {baslik: "🗺️ İlk Çağ Uygarlıkları Haritası", link: "materyaller/haritalar/ilk_cag_haritasi.jpg"},
    {baslik: "🧠 Tarih Bilimi Kavram Haritası", link: "materyaller/kavram_haritalari/tarih_kavram_haritasi.pdf"}
];

// --- 3. KLASİK (AÇIK UÇLU) SORULAR ---
const klasikSorular = [
    { 
        soru: "\"Ünlü tarihçi Herodot, tarihçiliğin babası olarak bilinir. O, 'Historia' adlı eserinde gezdiği yerleri, gördüğü halkları ve duyduğu efsaneleri anlatmıştır. Ancak Herodot olayları anlatırken neden ve sonuç ilişkisi kurmaktan ziyade, olayları hikayeleyici bir dille, kulaktan dolma bilgilere ve mitolojiye de yer vererek aktarmıştır.\"<br>Yukarıdaki metne göre, Herodot'un tarih yazıcılığı anlayışını 'Bilimsel Tarihçilik'ten ayıran en temel eksiklik nedir? Açıklayınız.", 
        cevap: "Herodot'un anlatımında 'neden-sonuç ilişkisinin' kurulmaması ve bilgilerin 'belgelere' değil, efsane ve duyumlara dayanması onu bilimsel tarihçilikten ayırır. Bilimsel tarih; belge, kanıt ve neden-sonuç ilişkisine dayanır, hikayecilikten uzaktır." 
    },
    { 
        soru: "\"Mısırlılar Nil Nehri'nin taşma zamanını hesaplamak için Güneş yılı esaslı takvimi, Sümerler ise dini ibadetlerini düzenlemek için Ay yılı esaslı takvimi icat etmişlerdir.\"<br>Bu bilgilere bakarak, insanoğlunun 'takvim' ve 'zaman ölçme' ihtiyacının ortaya çıkmasında hangi faktörlerin etkili olduğunu yazınız.", 
        cevap: "İnsanların takvimi icat etmesinde; tarımsal faaliyetleri düzenleme (Nil'in taşması, hasat zamanı) ve dini ibadetlerin zamanını belirleme (Sümerler) gibi 'ekonomik, coğrafi ve dini' ihtiyaçlar etkili olmuştur." 
    },
    { 
        soru: "\"Bir arkeolojik kazı sırasında toprak altından şu buluntular çıkarılmıştır: Kırık bir çömlek parçası, üzerinde resimler olan bir madeni para, yanmış buğday taneleri ve kilden yapılmış bir tablet.\"<br>Bu buluntuları 'Yazılı Kaynaklar' ve 'Yazısız (Kalıntı) Kaynaklar' olarak sınıflandırınız.", 
        cevap: "Yazılı Kaynaklar: Madeni para (üzerindeki yazılar varsa), Kil tablet. Yazısız (Kalıntı) Kaynaklar: Kırık çömlek parçası, Yanmış buğday taneleri." 
    },
    { 
        soru: "\"Tarih öğretmeni derste şu örneği vermiştir: 'Malazgirt Savaşı (1071) somut, başlangıcı ve bitişi belli bir gelişmedir. Ancak Anadolu'nun Türkleşmesi, bu savaşla başlayıp yüzyıllar süren genel bir süreçtir.'\" Metindeki örnekten yola çıkarak 'Tarihi Olay' ve 'Tarihi Olgu' kavramları arasındaki farkı bir cümle ile açıklayınız.", 
        cevap: "Tarihi Olay; kısa süreli, anlık ve somut gelişmelerdir (Savaş). Tarihi Olgu ise; olayların sonucunda ortaya çıkan, uzun sürece yayılan ve süreklilik gösteren soyut değişimlerdir (Türkleşme)." 
    },
    { 
        soru: "\"Orta Çağ Avrupa'sında veba salgını sırasında doktorlar, hastalığın 'kötü kokulardan' yayıldığını düşünerek gagalı maskeler takmış ve hastaları kan akıtarak tedavi etmeye çalışmışlardır. Bugün biz bunun tıbben yanlış olduğunu biliyoruz.\"<br>Bir tarihçi bu durumu incelerken 'O dönemin doktorları çok cahilmiş.' demek yerine nasıl bir yaklaşım sergilemelidir? 'Tarihsel Empati' kavramını kullanarak açıklayınız.", 
        cevap: "Tarihçi, geçmişi bugünün bilimsel bilgisiyle yargılamamalıdır (Anakronizm). Bunun yerine 'Tarihsel Empati' yaparak, o dönemin şartlarını, bilgi birikimini ve imkanlarını göz önüne almalı; doktorların o günkü mevcut bilgiyle ellerinden geleni yaptığını anlamaya çalışmalıdır." 
    },
    { 
        soru: "\"Kadeş Savaşı sonrasında Hitit kaynakları savaşı Hititlerin kazandığını, Mısır tapınak duvarları ise Mısırlıların kazandığını yazmaktadır.\"<br>Bu durum, tarih araştırmalarında 'tek bir kaynağa güvenmenin' sakıncalarını nasıl gösterir? Tarihçi gerçeğe ulaşmak için ne yapmalıdır?", 
        cevap: "Bu durum, kaynakların taraflı (subjektif) olabileceğini gösterir. Sadece tek tarafa bakmak tarihçiyi yanıltır. Tarihçi gerçeğe ulaşmak için 'Kaynak Karşılaştırması' (Terkip/Sentez öncesi Tenkit) yapmalı, farklı kaynakları kıyaslayarak ortak doğruları bulmalıdır." 
    },
    { 
        soru: "\"Ünlü tarihçi Halil İnalcık şöyle der: 'Gerçek bir tarihçi kaynaklara gitmek zorundadır. Arşivde belge bulmadan, sadece yorumlara dayalı yazılan tarih, roman olmaktan öteye gidemez.'\" Halil İnalcık bu sözüyle tarih biliminin hangi yöntem basamağının (5T) vazgeçilmez olduğunu vurgulamaktadır? Nedenini açıklayınız.", 
        cevap: "Halil İnalcık 'Tarama' (Kaynak Arama) basamağını ve belgelere dayanma zorunluluğunu vurgulamaktadır. Çünkü tarih, deney ve gözlem yapamaz; onun laboratuvarı belgelerdir. Belgesiz bilgi kanıtlanamaz, bilimsel nitelik taşımaz." 
    },
    { 
        soru: "\"Dijitalleşme sayesinde bugün binlerce yıllık el yazması eserlere evimizden tek tıkla ulaşabiliyoruz. Ancak internette dolaşan 'Tarihte ilk Türk uçağı 15. yüzyılda yapıldı' gibi sahte belgeler ve kurgu videolar da hızla yayılıyor.\"<br>Metne göre, dijital tarihçiliğin araştırmacılara sağladığı en büyük 'avantaj' ve yarattığı en büyük 'risk' nedir?", 
        cevap: "Avantaj: Bilgiye ve kaynaklara erişimin hızlanması, mekandan bağımsızlık (Erişilebilirlik). Risk: Bilgi kirliliği, manipüle edilmiş (sahte) belgelerin yayılması ve doğru bilgiyle yanlış bilginin birbirine karışması." 
    },
    { 
        soru: "\"Fuat Köprülü, Türk tarihinin sadece Osmanlı Hanedanı'nın siyasi olaylarından ibaret olmadığını savunmuştur. Ona göre Türk tarihi; edebiyatı, sanatı, ekonomisi, dini inanışları ve halkın yaşayışıyla bir bütün olarak incelenmelidir.\"<br>Fuat Köprülü'nün bu yaklaşımı, tarih yazımında 'Bütüncül Tarih' (Sosyal Tarih) anlayışı açısından neden önemlidir? Klasik siyasi tarih anlayışından farkını belirtiniz.", 
        cevap: "Klasik siyasi tarih sadece savaşları, antlaşmaları ve liderleri anlatır. Fuat Köprülü ise tarihin sadece devletin değil, 'milletin' tarihi olduğunu savunur. Toplumun kültürü, ekonomisi ve sanatı incelenmeden bir medeniyetin tam olarak anlaşılamayacağını belirtir. Bu, tarihi 'çok yönlü' ve 'bütüncül' ele almaktır." 
    },
    { 
        soru: "\"Tarihçi E.H. Carr, 'Tarih Nedir?' adlı eserinde şöyle der: 'Tarih, tarihçi ile olgular arasında kesintisiz bir diyalog sürecidir. Geçmişin bugünün gözüyle yeniden inşasıdır.'\" Bu söze göre tarih 'değişmez, donuk bir geçmiş' midir, yoksa 'yorumlanan bir süreç' midir? Tarihçinin bakış açısı (subjektifliği) tarihi bilgiyi nasıl etkiler? Tartışınız.", 
        cevap: "E.H. Carr'a göre tarih donuk bir geçmiş yığını değil, tarihçinin seçtiği ve yorumladığı dinamik bir süreçtir. Tarihçi, belgeleri seçerken ve yorumlarken kendi döneminin ve dünya görüşünün etkisinde kalır. Bu nedenle mutlak, %100 objektif bir tarih yoktur; tarihçinin süzgecinden geçmiş bir 'inşa' vardır. Her nesil tarihi kendi sorularıyla yeniden yazar." 
    }
];

// --- 4. ÇOKTAN SEÇMELİ TEST HAVUZU ---
const allTests = {
    test1: [
        {soru: "Aşağıdakilerden hangisi 'birinci elden kaynak' (ana kaynak) tanımına en uygundur?", secenekler: ["A) Ders kitabı", "B) Tarihi bir roman", "C) Fatih Sultan Mehmet'in yazdığı ferman", "D) Ansiklopedi", "E) Tarih öğretmeninin notları"], cevap: "C) Fatih Sultan Mehmet'in yazdığı ferman", aciklama: "Birinci elden kaynaklar, olayın geçtiği döneme ait olan ve olaya tanıklık eden kaynaklardır."},
        {soru: "Tarih bilimi olayları incelerken aşağıdakilerden hangisine BAŞVURMAZ?", secenekler: ["A) Belgelere", "B) Deney ve Gözleme", "C) Arkeolojik bulgulara", "D) Kronolojiye", "E) Coğrafi konuma"], cevap: "B) Deney ve Gözleme", aciklama: "Tarihi olaylar tekrarlanamadığı için deney yapılamaz."},
        {soru: "Tarih araştırmalarında kaynakların sınıflandırılmasına (zamana, mekana veya konuya göre ayırma) ne ad verilir?", secenekler: ["A) Tarama", "B) Tasnif", "C) Tahlil", "D) Tenkit", "E) Terkip"], cevap: "B) Tasnif", aciklama: "Tasnif sınıflandırma aşamasıdır."},
        {soru: "Aşağıdakilerden hangisi tarih öğrenmenin bireye sağladığı faydalardan biri DEĞİLDİR?", secenekler: ["A) Eleştirel düşünme becerisi kazandırır.", "B) Milli kimlik bilincini geliştirir.", "C) Geleceği kesin olarak tahmin etmeyi sağlar.", "D) Empati yeteneğini güçlendirir.", "E) Çok yönlü düşünmeyi sağlar."], cevap: "C) Geleceği kesin olarak tahmin etmeyi sağlar.", aciklama: "Tarih falcılık değildir, geleceği kesin bilemeyiz."},
        {soru: "Tarihsel bilginin üretim sürecinde 'Kaynak Arama' aşamasına verilen isim hangisidir?", secenekler: ["A) Terkip", "B) Tenkit", "C) Tahlil", "D) Tarama", "E) Tasnif"], cevap: "D) Tarama", aciklama: "İlk aşama kaynak taramasıdır."},
        {soru: "Aşağıdakilerden hangisi 'Sözlü Kaynaklar' grubuna girer?", secenekler: ["A) Kitabeler", "B) Destanlar", "C) Paralar", "D) Heykeller", "E) Fermanlar"], cevap: "B) Destanlar", aciklama: "Destanlar dilden dile aktarılan sözlü kaynaklardır."},
        {soru: "Dijitalleşmenin tarih araştırmalarına sağladığı en belirgin kolaylık aşağıdakilerden hangisidir?", secenekler: ["A) Bilgiye erişim hızını artırması", "B) Kaynakları tamamen yok etmesi", "C) Tarihçilere olan ihtiyacı bitirmesi", "D) Sadece yazılı kaynakları içermesi", "E) Tarihi olayları değiştirmesi"], cevap: "A) Bilgiye erişim hızını artırması", aciklama: "Dijital kütüphaneler sayesinde erişim hızı artmıştır."},
        {soru: "Tarihi bilgilerin değişebilir özellikte olması ne anlama gelir?", secenekler: ["A) Tarihin bir bilim dalı olmadığına", "B) Geçmişteki olayların sürekli değiştiğine", "C) Yeni belgeler bulundukça mevcut bilgilerin güncellenebileceğine", "D) Tarihçilerin keyfi yorum yaptığına", "E) Tarihi olayların tekrarlanabileceğine"], cevap: "C) Yeni belgeler bulundukça mevcut bilgilerin güncellenebileceğine", aciklama: "Tarihte mutlak değişmez bilgi yoktur, yeni belge bilgiyi değiştirebilir."},
        {soru: "Aşağıdakilerden hangisi tarih araştırmalarında kullanılan 'Yazılı Kaynaklar'dan biri değildir?", secenekler: ["A) Tabletler", "B) Beratlar", "C) Gazeteler", "D) Mağara duvar resimleri", "E) Yıllıklar"], cevap: "D) Mağara duvar resimleri", aciklama: "Mağara resimleri görsel/kalıntı kaynaktır (alfabe yoksa)."},
        {soru: "Bir tarihçinin araştırmasında kullandığı kaynağın güvenilir olup olmadığını incelediği aşama hangisidir?", secenekler: ["A) Tarama", "B) Tasnif", "C) Tenkit (Eleştiri)", "D) Terkip", "E) Tahlil"], cevap: "C) Tenkit (Eleştiri)", aciklama: "Güvenilirlik ve doğruluk Tenkit aşamasında sorgulanır."},
        {soru: "Halil İnalcık'ın 'Osmanlı İmparatorluğu Klasik Çağ' kitabı tarih metodolojisine göre nasıl sınıflandırılır?", secenekler: ["A) Birinci elden, sözlü kaynak", "B) İkinci elden, yazılı kaynak", "C) Birinci elden, yazılı kaynak", "D) İkinci elden, görsel kaynak", "E) Birinci elden, görsel kaynak"], cevap: "B) İkinci elden, yazılı kaynak", aciklama: "Olaydan sonra belgelerle yazıldığı için ikinci el kaynaktır."},
        {soru: "Tarihsel bilginin üretim sürecinde 'Terkip' (Sentez) aşaması neden en son sırada yer alır?", secenekler: ["A) Kaynak bulmak çok zor olduğu için", "B) Elde edilen bilgilerin sınıflandırılması gerektiği için", "C) Doğruluğu kanıtlanmış bilgilerin birleştirilerek eserin yazıldığı aşama olduğu için", "D) Eleştiri yapmadan eser yazılamayacağı için", "E) Sadece sözlü kaynakların kullanıldığı aşama olduğu için"], cevap: "C) Doğruluğu kanıtlanmış bilgilerin birleştirilerek eserin yazıldığı aşama olduğu için", aciklama: "Terkip, tüm araştırmanın birleştirilip eserin yazıldığı son aşamadır."},
        {soru: "Büyük Veri (Big Data) kullanımının tarihçilere sunduğu avantaj nedir?", secenekler: ["A) Belgelerin orijinalliğinin bozulması", "B) Milyonlarca veriyi analiz ederek daha önce fark edilmeyen örüntüleri keşfetme imkanı", "C) Sadece son 10 yılın tarihinin araştırılabilmesi", "D) Kütüphanelere gitme zorunluluğunun tamamen kalkması", "E) Yabancı dil bilme gerekliliğinin ortadan kalkması"], cevap: "B) Milyonlarca veriyi analiz ederek daha önce fark edilmeyen örüntüleri keşfetme imkanı", aciklama: "Büyük veri analizi insan gözüyle görülemeyen ilişkileri ortaya çıkarır."},
        {soru: "Bir araştırmacının hem Türk hem İngiliz raporlarını okuması tarih biliminin hangi ilkesiyle ilgilidir?", secenekler: ["A) Yer ve zaman belirtme", "B) Objektiflik (Nesnellik)", "C) Deney yapma", "D) Tasnif etme", "E) Sentez yapma"], cevap: "B) Objektiflik (Nesnellik)", aciklama: "Çapraz okuma yapmak tarafsızlığı (objektifliği) sağlar."},
        {soru: "Aşağıdaki eşleştirmelerden hangisi YANLIŞTIR?", secenekler: ["A) Ferman - Yazılı Kaynak", "B) Menkıbe - Sözlü Kaynak", "C) Arkeolojik Çömlek - Kalıntı/Nesne", "D) İstiklal Madalyası - Yazılı Kaynak", "E) Minyatür - Görsel Kaynak"], cevap: "D) İstiklal Madalyası - Yazılı Kaynak", aciklama: "Madalya bir nesnedir, yazılı kaynak sayılmaz."},
        {soru: "'Tarih, milletlerin hafızasıdır.' sözü hangisine vurgu yapmaktadır?", secenekler: ["A) Ekonomik kalkınmaya", "B) Teknolojik gelişime", "C) Milli kültürün ve kimliğin nesilden nesile aktarılmasına", "D) Askeri gücün artırılmasına", "E) Coğrafi sınırların genişlemesine"], cevap: "C) Milli kültürün ve kimliğin nesilden nesile aktarılmasına", aciklama: "Tarih toplumsal hafızayı ve kimliği korur."},
        {soru: "Tahlil aşamasında veriler yetersiz bulunursa ne yapılmalıdır?", secenekler: ["A) Araştırmayı sonlandırmalıdır.", "B) 'Tarama' aşamasına geri dönerek yeni kaynaklar aramalıdır.", "C) Kendi yorumlarıyla boşlukları doldurmalıdır.", "D) Eseri hemen kaleme almalıdır.", "E) Kaynakları imha etmelidir."], cevap: "B) 'Tarama' aşamasına geri dönerek yeni kaynaklar aramalıdır.", aciklama: "Bilgi eksikse sentez yapılamaz, başa dönüp kaynak aranır."},
        {soru: "Dijital arşivlerdeki 'Bilgi Kirliliği'ne karşı tarihçi ne yapmalıdır?", secenekler: ["A) Sadece basılı kaynak kullanmalıdır.", "B) İnternette bulduğu ilk bilgiye güvenmelidir.", "C) Dijital veriyi, Tenkit (Eleştiri) süzgecinden geçirip doğrulamalıdır.", "D) Dijitalleşmeyi reddetmelidir.", "E) Wikipedia'yı tek kaynak olarak almalıdır."], cevap: "C) Dijital veriyi, Tenkit (Eleştiri) süzgecinden geçirip doğrulamalıdır.", aciklama: "Her bilgi doğru değildir, teyit edilmelidir."},
        {soru: "Bir tarihçinin sadece raporları değil, şiirleri ve fotoğrafları da incelemesi neyi amaçladığını gösterir?", secenekler: ["A) Olayı sadece edebi açıdan incelemeyi", "B) Tarihi olayı çok yönlü ve bütüncül kavramayı", "C) Askeri belgelerin yanlış olduğunu kanıtlamayı", "D) Araştırmayı kısa sürede bitirmeyi", "E) Sadece görsel öğeler kullanmayı"], cevap: "B) Tarihi olayı çok yönlü ve bütüncül kavramayı", aciklama: "Farklı kaynak türleri olaya bütüncül bakmayı sağlar."},
        {soru: "Eski paraları inceleyen bilim dalı hangisidir?", secenekler: ["A) Paleografya", "B) Nümizmatik", "C) Epigrafya", "D) Antropoloji", "E) Filoloji"], cevap: "B) Nümizmatik", aciklama: "Nümizmatik (Meskukat) para bilimidir."},
        {soru: "İnsanların kendi aile tarihlerini dijital platformlara yüklemesinin tarih bilimine katkısı nedir?", secenekler: ["A) Resmi tarihin tek kaynak olmasını sağlar.", "B) Yerel ve sözlü tarih unsurlarının kaybolmasını engeller.", "C) Tarihçilerin işsiz kalmasına neden olur.", "D) Tarihi olayların önemini azaltır.", "E) Sadece devletlerin tarihinin yazılmasını sağlar."], cevap: "B) Yerel ve sözlü tarih unsurlarının kaybolmasını engeller.", aciklama: "Halkın tarihi (sosyal tarih) bu sayede kaybolmaz."},
        {soru: "Aşağıdaki ifadelerden hangisi tarihsel empati kurmaya bir örnektir?", secenekler: ["A) 'İstanbul'un fethinde neden uçak kullanılmadı?' demek.", "B) 'O dönemin şartlarında Fatih gemileri karadan yürütmek zorundaydı.' diyebilmek.", "C) 'Eski insanlar teknolojiden anlamıyordu.' demek.", "D) Geçmişi bugünün ahlak kurallarıyla yargılamak.", "E) Tarihi olayları tamamen yok saymak."], cevap: "B) 'O dönemin şartlarında Fatih gemileri karadan yürütmek zorundaydı.' diyebilmek.", aciklama: "Empati, olayı o günün şartlarına göre değerlendirmektir."},
        {soru: "'Bu belgenin kağıt ve mürekkep yapısı o döneme ait mi?' sorusu hangi tenkit türüne girer?", secenekler: ["A) İç Tenkit", "B) Dış Tenkit", "C) Sözlü Tenkit", "D) Tahlil", "E) Terkip"], cevap: "B) Dış Tenkit", aciklama: "Fiziksel özellikler Dış Tenkit konusudur."},
        {soru: "Dijital oyunlar ve dizilerin yanlış bilgi içermesi eğitimde nasıl bir sonuç doğurur?", secenekler: ["A) Tarih dersine gerek kalmaz.", "B) Öğrencilerde 'gerçeklik' ile 'kurgu' ayrımını yapma becerisi zorunluluğu doğar.", "C) Tarihi kaynakların hepsi yakılmalıdır.", "D) Sadece dizilerden tarih öğrenilmelidir.", "E) Dijital oyunlar yasaklanmalıdır."], cevap: "B) Öğrencilerde 'gerçeklik' ile 'kurgu' ayrımını yapma becerisi zorunluluğu doğar.", aciklama: "Medya okuryazarlığı ile kurgu ve gerçek ayırt edilmelidir."},
        {soru: "Bir döneme ait yazılı belge bulunamazsa tarihçi ne yapmalıdır?", secenekler: ["A) Araştırmayı iptal etmelidir.", "B) Olayları hayal gücüyle yazmalıdır.", "C) Yabancı devlet kaynaklarına ve arkeolojiye yönelmelidir.", "D) Sadece sözlü efsaneleri doğru kabul etmelidir.", "E) Dönemi kitaplardan çıkarmalıdır."], cevap: "C) Yabancı devlet kaynaklarına ve arkeolojiye yönelmelidir.", aciklama: "Çapraz okuma ve arkeoloji ile eksikler tamamlanır."},
        {soru: "Bir yazarın eserinde sürekli kendi milletini yüceltmesi iç tenkitte hangi sorunun cevabıdır?", secenekler: ["A) Belgenin fiziksel durumu nasıldır?", "B) Belge hangi tarihte basılmıştır?", "C) Yazar olaylara objektif yaklaşmış mıdır?", "D) Belgedeki terimler günümüze uygun mudur?", "E) Belge nerede saklanmaktadır?"], cevap: "C) Yazar olaylara objektif yaklaşmış mıdır?", aciklama: "Yazarın taraflılığı iç tenkit konusudur."},
        {soru: "'Born-digital' (Doğuştan dijital) kaynak kavramına en doğru örnek hangisidir?", secenekler: ["A) Fatih Fermanı'nın taranması", "B) Lozan Antlaşması'nın fotoğrafı", "C) Bir devlet başkanının sosyal medya hesabından yaptığı resmi açıklama", "D) Eski bir gazetenin taranması", "E) Bir heykelin 3D modellemesi"], cevap: "C) Bir devlet başkanının sosyal medya hesabından yaptığı resmi açıklama", aciklama: "Doğuştan dijitallerin kağıt aslı yoktur (Tweet, E-posta vb)."},
        {soru: "'Tarih, geçmişin kendisi değil, tarihçi tarafından yeniden inşasıdır' sözü neyi vurgular?", secenekler: ["A) Tarihin tamamen uydurma olduğunu", "B) Geçmişin olduğu gibi aktarılmasının imkansız olduğunu, tarihçinin bakış açısının etkili olduğunu", "C) Tarihçilerin geçmişi değiştirebileceğini", "D) Tarihte kesin kanunların olduğunu", "E) Herkesin tarihçi olabileceğini"], cevap: "B) Geçmişin olduğu gibi aktarılmasının imkansız olduğunu, tarihçinin bakış açısının etkili olduğunu", aciklama: "Tarih, tarihçinin seçtiği ve yorumladığı bir kurgudur."},
        {soru: "Aşağıdaki senaryoların hangisinde anakronizm (tarih yanılgısı) yapılmıştır?", secenekler: ["A) Sümerlerin yazıyı kullanması", "B) Mısırlıların piramit yapması", "C) Mete Han'ın ordusunu düzenlemesi", "D) Malazgirt Savaşı'nda 'milliyetçilik' akımından etkilenilmesi", "E) Osmanlıların İstanbul'u kuşatması"], cevap: "D) Malazgirt Savaşı'nda 'milliyetçilik' akımından etkilenilmesi", aciklama: "Milliyetçilik 1789'da çıkmıştır, 1071'de olamaz."},
        {soru: "Dijitalleşme ile tarih yazımında 'Demokratikleşme' neyi ifade eder?", secenekler: ["A) Sadece demokratik ülkelerin tarihini", "B) Tarihsel bilginin akademisyenlerin tekelinden çıkıp halka açılmasını", "C) Seçim sonuçlarının saklanmasını", "D) Tarihçilerin oylama ile seçilmesini", "E) Herkesin tarihi değiştirebilmesini"], cevap: "B) Tarihsel bilginin akademisyenlerin tekelinden çıkıp halka açılmasını", aciklama: "Bilgiye erişim herkes için mümkün hale gelmiştir."}
    ],
    test2: [
        {soru: "İnsan topluluklarının geçmişteki yaşayışlarını, kültürlerini, birbirleriyle olan ilişkilerini yer ve zaman göstererek, neden-sonuç ilişkisi içinde inceleyen bilim dalı aşağıdakilerden hangisidir?", secenekler: ["A) Sosyoloji", "B) Tarih", "C) Arkeoloji", "D) Coğrafya", "E) Felsefe"], cevap: "B) Tarih", aciklama: "Verilen tanım, tarih biliminin en temel ve kapsamlı tanımıdır."}, 
        {soru: "Tarih öncesi dönemlerin (yazının icadından önceki devirler) aydınlatılmasında tarih bilimine en çok yardımcı olan bilim dalı hangisidir?", secenekler: ["A) Diplomasi", "B) Nümizmatik", "C) Paleografya", "D) Arkeoloji", "E) Epigrafya"], cevap: "D) Arkeoloji", aciklama: "Yazı yoksa arkeoloji (kazı) en önemli kaynaktır."}, 
        {soru: "Türklerin tarih boyunca kullandığı takvimlerden hangisi 'Ay Yılı' esaslıdır?", secenekler: ["A) 12 Hayvanlı Türk Takvimi", "B) Celali Takvim", "C) Hicri Takvim", "D) Rumi Takvim", "E) Miladi Takvim"], cevap: "C) Hicri Takvim", aciklama: "Sadece Hicri takvim Ay yılına göredir."}, 
        {soru: "Tarihi olayların zamanının belirlenmesinde ve sıralanmasında tarihe yardımcı olan 'Zaman Bilimi' aşağıdakilerden hangisidir?", secenekler: ["A) Kronoloji", "B) Coğrafya", "C) Etnografya", "D) Heraldik", "E) Kimya"], cevap: "A) Kronoloji", aciklama: "Kronoloji zaman ve sıralama bilimidir."}, 
        {soru: "Tarih biliminin konusu aşağıdakilerden hangisini kapsamaz?", secenekler: ["A) Savaşlar ve barışlar", "B) Depremlerin oluşum mekanizması", "C) Göçler", "D) İbadet şekilleri", "E) Devlet yönetimleri"], cevap: "B) Depremlerin oluşum mekanizması", aciklama: "Doğa olaylarının oluşumu Fen bilimlerinin konusudur."}, 
        {soru: "Aşağıdakilerden hangisi tarih araştırmalarında kullanılan 'Görsel Kaynaklar' grubunda yer alır?", secenekler: ["A) Tabletler", "B) Fotoğraflar", "C) Efsaneler", "D) Şecereler", "E) Halılar"], cevap: "B) Fotoğraflar", aciklama: "Fotoğraf görseldir. Tablet yazılı, efsane sözlüdür."}, 
        {soru: "Tarih araştırmalarında elde edilen verilerin 'yer, zaman ve konu' bakımından bölümlere ayrılması işlemine ne ad verilir?", secenekler: ["A) Tarama", "B) Tenkit", "C) Terkip", "D) Tasnif", "E) Tahlil"], cevap: "D) Tasnif", aciklama: "Tasnif sınıflandırma demektir."}, 
        {soru: "Günümüzde kullandığımız Miladi Takvim'in başlangıcı (0 yılı) olarak hangi olay kabul edilir?", secenekler: ["A) Hicret", "B) Hz. İsa'nın doğumu", "C) Yazının icadı", "D) İstanbul'un Fethi", "E) Fransız İhtilali"], cevap: "B) Hz. İsa'nın doğumu", aciklama: "Miladi takvim Hz. İsa'nın doğumunu esas alır."}, 
        {soru: "Dijitalleşme ile birlikte tarihçilerin en çok kullandığı 'arama' yöntemi aşağıdakilerden hangisine dönüşmüştür?", secenekler: ["A) Kütüphane fişlerini tek tek elle tarama", "B) Sadece sözlü görüşmeler yapma", "C) Anahtar kelimelerle dijital veritabanlarında sorgulama yapma", "D) Kazı yapma", "E) Müze gezme"], cevap: "C) Anahtar kelimelerle dijital veritabanlarında sorgulama yapma", aciklama: "Artık anahtar kelimelerle (keywords) arama yapılmaktadır."}, 
        {soru: "'Tarih tekerrürden ibarettir' sözü ne anlama gelmektedir?", secenekler: ["A) Tarihi olayların aynen tekrarlandığı", "B) Tarihte benzer sebeplerin benzer sonuçlar doğurabileceği", "C) Tarihçilerin hep aynı şeyleri yazdığı", "D) Tarihin bir bilim olmadığı", "E) Geçmişin unutulması gerektiği"], cevap: "B) Tarihte benzer sebeplerin benzer sonuçlar doğurabileceği", aciklama: "Benzer hatalar benzer sonuçları doğurur."}, 
        {soru: "Aşağıdakilerden hangisi 'Tarihi Olay' (Vaka) ile 'Tarihi Olgu' (Vakıa) arasındaki farkı en iyi açıklar?", secenekler: ["A) Olay uzun sürelidir, olgu kısa sürelidir.", "B) Olay somut ve başlangıcı-bitişi bellidir, olgu ise bu olayların sonucunda oluşan uzun süreli genel süreçtir.", "C) Olaylar tekrarlanabilir, olgular tekrarlanamaz.", "D) Olayları tarihçiler yazar, olguları sosyologlar yazar.", "E) Malazgirt Savaşı bir olgudur, Anadolu'nun Türkleşmesi bir olaydır."], cevap: "B) Olay somut ve başlangıcı-bitişi bellidir, olgu ise bu olayların sonucunda oluşan uzun süreli genel süreçtir.", aciklama: "Olay anlık, olgu süreçtir."}, 
        {soru: "Tarihçi, eserini yazarken dipnot kullanmaya ve kaynakça belirtmeye büyük özen göstermektedir. Bu durum tarihçinin hangi özelliğini kanıtlar?", secenekler: ["A) Edebi yeteneğini", "B) Bilimsel ahlaka ve dürüstlüğe (etik) uygun çalıştığını", "C) Çok fazla kitap okuduğunu", "D) Yabancı dil bildiğini", "E) Konuyu çok iyi bildiğini"], cevap: "B) Bilimsel ahlaka ve dürüstlüğe (etik) uygun çalıştığını", aciklama: "Referans vermek bilimsel dürüstlüktür."}, 
        {soru: "Türkler İslamiyet'i kabul ettikten sonra, dini ibadetlerin zamanını belirleyebilmek (Hac, Oruç vb.) amacıyla hangi takvimi kullanmaya başlamışlardır?", secenekler: ["A) 12 Hayvanlı Türk Takvimi", "B) Miladi Takvim", "C) Rumi Takvim", "D) Hicri Takvim", "E) Celali Takvim"], cevap: "D) Hicri Takvim", aciklama: "Dini ibadetler Hicri takvime göre yapılır."}, 
        {soru: "Tarihi bir belgenin okunabilmesi için eski yazıların ve alfabelerin bilinmesi gerekir. Bu konuda tarihçiye yardımcı olan bilim dalı hangisidir?", secenekler: ["A) Paleografya", "B) Nümizmatik", "C) Antropoloji", "D) Heraldik", "E) Kimya"], cevap: "A) Paleografya", aciklama: "Paleografya eski yazı bilimidir."}, 
        {soru: "Osmanlı Devleti'nde mali (ekonomik) işlerin düzenlenmesi amacıyla, Güneş yılı esas alınarak hazırlanan takvim hangisidir?", secenekler: ["A) Hicri Takvim", "B) Rumi Takvim", "C) Celali Takvim", "D) 12 Hayvanlı Türk Takvimi", "E) Miladi Takvim"], cevap: "B) Rumi Takvim", aciklama: "Osmanlı'da mali işler için Rumi Takvim kullanılmıştır."}, 
        {soru: "5T kuralına göre 'Tahlil' aşamasında elde edilen veriler yeterli bulunmazsa ne yapılmalıdır?", secenekler: ["A) Terkip aşamasına geçilmelidir.", "B) Eldeki verilerle yetinilmelidir.", "C) Tarama (Kaynak arama) aşamasına geri dönülmelidir.", "D) Konu değiştirilmelidir.", "E) Tenkit yapılmadan eser yazılmalıdır."], cevap: "C) Tarama (Kaynak arama) aşamasına geri dönülmelidir.", aciklama: "Veri eksikse başa dönüp kaynak aranır."}, 
        {soru: "Tarih öğrenimi, bireylerde 'Empati' yeteneğini geliştirir. Bu yetenek bireye günlük hayatta nasıl bir katkı sağlar?", secenekler: ["A) Olayları sadece kendi penceresinden görmesini sağlar.", "B) Farklı kültürlere ve insanlara karşı önyargısız ve hoşgörülü yaklaşmasını sağlar.", "C) Geçmişte yaşamak istemesine neden olur.", "D) Sadece kendi milletini sevmesini sağlar.", "E) Ekonomik kazanç sağlar."], cevap: "B) Farklı kültürlere ve insanlara karşı önyargısız ve hoşgörülü yaklaşmasını sağlar.", aciklama: "Empati hoşgörüyü artırır."}, 
        {soru: "Dijital tarihçilikte 'Born-digital' (Doğuştan dijital) olmayan, sonradan dijitalleştirilmiş kaynaklara ne ad verilir?", secenekler: ["A) Birinci el kaynak", "B) Dijitalleştirilmiş (Digitized) kaynak", "C) Sözlü kaynak", "D) Yapay zeka", "E) Büyük veri"], cevap: "B) Dijitalleştirilmiş (Digitized) kaynak", aciklama: "Sonradan tarananlar 'dijitalleştirilmiş' kaynaktır."}, 
        {soru: "Müzelerde bulunan eski paralar, mühürler ve armalar tarihçiye hangi açıdan bilgi VERMEZ?", secenekler: ["A) Dönemin ekonomik durumu", "B) Hükümdarın saltanat sembolleri", "C) Devletin sanatsal anlayışı", "D) Olayın geçtiği günün hava durumu", "E) Kullanılan yazı ve alfabe"], cevap: "D) Olayın geçtiği günün hava durumu", aciklama: "Paralar iklim hakkında bilgi vermez."}, 
        {soru: "Tarih araştırmalarında 'Terkip' (Sentez) aşaması neden bir yapbozun parçalarını birleştirmeye benzetilir?", secenekler: ["A) Parçalar her zaman eksik olduğu için", "B) Farklı kaynaklardan doğrulanan bilgilerin anlamlı bir bütün haline getirildiği aşama olduğu için", "C) Çok eğlenceli olduğu için", "D) Rastgele yapıldığı için", "E) Hata kabul etmediği için"], cevap: "B) Farklı kaynaklardan doğrulanan bilgilerin anlamlı bir bütün haline getirildiği aşama olduğu için", aciklama: "Bilgiler birleştirilerek anlamlı bir bütün oluşturulur."}, 
        {soru: "Karbon-14 metodu, tarihçilere hangi konuda kesin kanıtlar sunar?", secenekler: ["A) Bir metnin yazarının kim olduğu", "B) Tarihi bir savaşın nedenleri", "C) Organik buluntuların (kemik, ahşap vb.) yaşı", "D) Bir toplumun dini inançları", "E) Kültürel etkileşimler"], cevap: "C) Organik buluntuların (kemik, ahşap vb.) yaşı", aciklama: "C-14 yaş tayininde kullanılır."}, 
        {soru: "Dijitalleşmenin tarih araştırmalarına getirdiği 'Erişilebilirlik' kolaylığı, beraberinde hangi zorluğu getirmiştir?", secenekler: ["A) Kaynak bulamama", "B) Bilgi kirliliği ve güvenilirlik sorunu", "C) Kütüphanelerin kapanması", "D) Tarihçilerin sayısının azalması", "E) Kitap okumanın yasaklanması"], cevap: "B) Bilgi kirliliği ve güvenilirlik sorunu", aciklama: "Her bilgi doğru değildir, kirlilik artmıştır."}, 
        {soru: "Bir tarihçi Orta Asya Türk tarihini araştırırken Çin kaynaklarına da bakmak zorundadır. Bunun temel nedeni nedir?", secenekler: ["A) Çin kaynaklarının daha süslü olması", "B) Türklerin o dönemde yazılı hayata geçmemiş olması ve yerleşik Çinlilerin Türkler hakkında kayıt tutması", "C) Çince öğrenmek istemesi", "D) Türk kaynaklarının yasaklanmış olması", "E) Çinlilerin Türkleri çok sevmesi"], cevap: "B) Türklerin o dönemde yazılı hayata geçmemiş olması ve yerleşik Çinlilerin Türkler hakkında kayıt tutması", aciklama: "Türkler göçebe olduğu için az yazılı belge bırakmıştır."}, 
        {soru: "Aşağıdakilerden hangisi 'İkinci El Kaynak' örneğidir?", secenekler: ["A) Halil İnalcık'ın yazdığı tarih kitabı", "B) İstiklal Savaşı'nda kullanılan bir tüfek", "C) Lidyalılara ait bir para", "D) Kadeş Antlaşması tableti", "E) Orhun Abideleri"], cevap: "A) Halil İnalcık'ın yazdığı tarih kitabı", aciklama: "Tarih kitapları, belgeler incelenerek yazıldığı için ikinci eldir."}, 
        {soru: "Tarih biliminde 'Genelleme Yapılamaz' ilkesi neyi ifade eder?", secenekler: ["A) Tarihi olayların hepsi birbirinin aynısıdır.", "B) Bir olaydaki kural, başka bir olaya aynen uygulanamaz; her olay kendine has koşullar taşır.", "C) Bütün savaşların sonucu aynıdır.", "D) Tarihçiler genel konuşmayı sever.", "E) Tarih fen bilimleri gibidir, formülleri vardır."], cevap: "B) Bir olaydaki kural, başka bir olaya aynen uygulanamaz; her olay kendine has koşullar taşır.", aciklama: "Tarihte her olay özgündür, formülize edilemez."}, 
        {soru: "Tarihsel bilginin 'mutlak doğru' (değişmez) olmamasının temel sebebi nedir?", secenekler: ["A) Tarihçilerin sürekli yalan söylemesi", "B) Tarihsel belgelerin eksik kalabilmesi ve yeni bulunan belgelerin mevcut bilgiyi değiştirme potansiyeli", "C) Geçmişin önemsiz olması", "D) Devletlerin tarihi sürekli değiştirmesi", "E) Tarihin bilim olmaması"], cevap: "B) Tarihsel belgelerin eksik kalabilmesi ve yeni bulunan belgelerin mevcut bilgiyi değiştirme potansiyeli", aciklama: "Yeni bulunan belge eski bilgiyi değiştirebilir."}, 
        {soru: "Dijital tarihçilikte kullanılan 'Veri Madenciliği' (Data Mining) yöntemi tarihçiye ne sağlar?", secenekler: ["A) Toprağı kazıp tarihi eser bulmayı", "B) Büyük veri yığınları içindeki gizli örüntüleri, ilişkileri ve eğilimleri bilgisayar algoritmalarıyla ortaya çıkarmayı", "C) Sadece resimleri taramayı", "D) Bilgisayar oyunları tasarlamayı", "E) Eski bilgisayarları tamir etmeyi"], cevap: "B) Büyük veri yığınları içindeki gizli örüntüleri, ilişkileri ve eğilimleri bilgisayar algoritmalarıyla ortaya çıkarmayı", aciklama: "Veri madenciliği büyük verideki gizli örüntüleri bulur."}, 
        {soru: "'Tarih yazmak, tarih yapmak kadar mühimdir...' sözüyle Atatürk hangi ilkeye vurgu yapmıştır?", secenekler: ["A) Öznellik", "B) Objektiflik (Nesnellik)", "C) Anakronizm", "D) Edebi üslup", "E) Kronolojik sıralama"], cevap: "B) Objektiflik (Nesnellik)", aciklama: "Olayı olduğu gibi aktarmak objektifliktir."}, 
        {soru: "Tarih araştırmalarında 'Nedensellik' (Determinizm) ilkesi incelenirken dikkat edilmesi gereken en önemli nokta nedir?", secenekler: ["A) Her olayın sadece tek bir nedeni olduğunu savunmak", "B) Olayların tek bir nedene indirgenemeyeceğini, çok boyutlu (siyasi, ekonomik, sosyal) nedenler zinciri olduğunu görmek", "C) Nedenlerin sonuçlardan daha önemsiz olduğunu düşünmek", "D) Sadece kahramanların kararlarına odaklanmak", "E) Olayları tesadüflere bağlamak"], cevap: "B) Olayların tek bir nedene indirgenemeyeceğini, çok boyutlu (siyasi, ekonomik, sosyal) nedenler zinciri olduğunu görmek", aciklama: "Olayların çok boyutlu nedenleri vardır."}, 
        {soru: "Sözlü tarihin en büyük 'handikapı' (dezavantajı) nedir?", secenekler: ["A) Kaynak kişiye ulaşmanın zor olması", "B) İnsan hafızasının yanıltıcı olabilmesi ve anlatıcının olayları kendi açısından (sübjektif) hatırlaması", "C) Ses kayıt cihazlarının pahalı olması", "D) Sözlü tarihin çok zaman alması", "E) Kimsenin konuşmak istememesi"], cevap: "B) İnsan hafızasının yanıltıcı olabilmesi ve anlatıcının olayları kendi açısından (sübjektif) hatırlaması", aciklama: "Hafıza yanıltıcı olabilir, teyit gerektirir."}
    ],
    test3: [
        {soru: "Tarih biliminin yöntemi, diğer pozitif bilimlerden (Fizik, Kimya vb.) hangi yönüyle temelden ayrılır?", secenekler: ["A) Gözlem yapmasıyla", "B) Deney yapılamamasıyla", "C) Rapor tutmasıyla", "D) Araştırma yapmasıyla", "E) Sonuç çıkarmasıyla"], cevap: "B) Deney yapılamamasıyla", aciklama: "Tarihte deney yapılamaz."}, 
        {soru: "'Olay' (Vaka) ve 'Olgu' (Vakıa) kavramları düşünüldüğünde, aşağıdakilerden hangisi bir 'Tarihi Olay' örneğidir?", secenekler: ["A) Anadolu'nun Türkleşmesi", "B) Türkiye'nin çağdaşlaşması", "C) İstanbul'un Fethi (1453)", "D) İslamiyet'in yayılması", "E) Milliyetçilik akımının güçlenmesi"], cevap: "C) İstanbul'un Fethi (1453)", aciklama: "İstanbul'un Fethi somut bir olaydır."}, 
        {soru: "Tarih araştırmalarında 'birinci elden kaynak' (ana kaynak) aşağıdakilerden hangisidir?", secenekler: ["A) Olayın geçtiği döneme ait her türlü bulgu ve belge", "B) Ders kitapları", "C) Ansiklopediler", "D) Tarihi romanlar", "E) Öğretmen notları"], cevap: "A) Olayın geçtiği döneme ait her türlü bulgu ve belge", aciklama: "O döneme ait her şey birinci eldir."}, 
        {soru: "Türklerin kullandığı takvimlerden hangisi 'Güneş Yılı' esasına dayanmaz?", secenekler: ["A) 12 Hayvanlı Türk Takvimi", "B) Celali Takvim", "C) Rumi Takvim", "D) Hicri Takvim", "E) Miladi Takvim"], cevap: "D) Hicri Takvim", aciklama: "Hicri takvim Ay yılı esaslıdır."}, 
        {soru: "Tarihi olayların doğru değerlendirilebilmesi için olayın geçtiği 'yer' ve 'zaman'ın bilinmesi neden zorunludur?", secenekler: ["A) Ezber yapmayı kolaylaştırmak için", "B) Olayın neden-sonuç ilişkisini kurabilmek ve o günün şartlarına göre değerlendirebilmek için", "C) Kitapları kalınlaştırmak için", "D) Sadece savaşları incelemek için", "E) Harita çizebilmek için"], cevap: "B) Olayın neden-sonuç ilişkisini kurabilmek ve o günün şartlarına göre değerlendirebilmek için", aciklama: "Yer ve zaman, olayın bağlamını kurmayı sağlar."}, 
        {soru: "Aşağıdakilerden hangisi 'Tarih Yazıcılığı' türlerinden biri olan 'Hikayeci Tarih'in en bilinen temsilcisidir?", secenekler: ["A) Heredot", "B) Halil İnalcık", "C) Thukydides", "D) İlber Ortaylı", "E) Voltaire"], cevap: "A) Heredot", aciklama: "Heredot hikayeci tarihin babasıdır."}, 
        {soru: "Eski paraları inceleyerek tarihe yardımcı olan bilim dalı hangisidir?", secenekler: ["A) Coğrafya", "B) Nümizmatik", "C) Kimya", "D) Biyoloji", "E) Sosyoloji"], cevap: "B) Nümizmatik", aciklama: "Nümizmatik para bilimidir."}, 
        {soru: "Tarih araştırmasının 5T basamağından ilki olan 'Tarama' ne anlama gelir?", secenekler: ["A) Kaynakların okunması", "B) Kaynakların sınıflandırılması", "C) Kaynak arama ve toplama", "D) Kaynakların eleştirilmesi", "E) Eserin yazılması"], cevap: "C) Kaynak arama ve toplama", aciklama: "Tarama kaynak toplama işidir."}, 
        {soru: "Aşağıdaki takvimlerden hangisi Türklerin İslamiyet'i kabulünden ÖNCE kullandığı takvimdir?", secenekler: ["A) Hicri Takvim", "B) Rumi Takvim", "C) Celali Takvim", "D) 12 Hayvanlı Türk Takvimi", "E) Miladi Takvim"], cevap: "D) 12 Hayvanlı Türk Takvimi", aciklama: "İslamiyet öncesi 12 Hayvanlı Türk Takvimi kullanılmıştır."}, 
        {soru: "Dijital kütüphanelerin araştırmacılara sağladığı 'mekandan bağımsızlık' ne demektir?", secenekler: ["A) Kütüphanelerin kapanması", "B) Araştırmacının evinden veya ofisinden dünyanın herhangi bir yerindeki arşive ulaşabilmesi", "C) Sadece uzayla ilgili araştırma yapılması", "D) Tarihçilerin seyahat etmesinin yasaklanması", "E) Binaların yıkılması"], cevap: "B) Araştırmacının evinden veya ofisinden dünyanın herhangi bir yerindeki arşive ulaşabilmesi", aciklama: "İnternet sayesinde her yerden erişim mümkündür."}, 
        {soru: "Fatih Sultan Mehmet dönemini araştıran bir tarihçinin, o döneme ait 'altın paraları' ve 'fermanları' incelemesi, aşağıdaki kaynak türlerinden hangilerine başvurduğunu gösterir?", secenekler: ["A) Sadece Sözlü Kaynaklar", "B) Yazılı Kaynaklar ve Kalıntı/Nesne Kaynaklar", "C) Sadece Görsel Kaynaklar", "D) İkinci El Kaynaklar", "E) Dijital Kaynaklar"], cevap: "B) Yazılı Kaynaklar ve Kalıntı/Nesne Kaynaklar", aciklama: "Ferman yazılı, para nesne kaynaktır."}, 
        {soru: "Tarih biliminde 'Neden-Sonuç' ilişkisi neden bu kadar önemlidir?", secenekler: ["A) Olayları ezberlemeyi kolaylaştırdığı için", "B) Tarihi bir masal olmaktan çıkarıp, olaylar arasındaki sürekliliği ve mantıksal bağı kurduğu için", "C) Tarihçilerin işini zorlaştırdığı için", "D) Sınav soruları hazırlamak için", "E) Geleceği kesin olarak bilmek için"], cevap: "B) Tarihi bir masal olmaktan çıkarıp, olaylar arasındaki sürekliliği ve mantıksal bağı kurduğu için", aciklama: "Nedensellik olaylar arası bağı kurar."}, 
        {soru: "Celali Takvim ve Rumi Takvim'in ortak özelliği aşağıdakilerden hangisidir?", secenekler: ["A) İkisinin de Ay yılı esaslı olması", "B) İkisinin de sadece Türkler tarafından kullanılması", "C) İkisinin de mali (ekonomik) işleri düzenlemek amacıyla hazırlanmış Güneş yılı esaslı takvimler olması", "D) Başlangıçlarının Hz. İsa'nın doğumu olması", "E) Günümüzde hala resmi takvim olarak kullanılmaları"], cevap: "C) İkisinin de mali (ekonomik) işleri düzenlemek amacıyla hazırlanmış Güneş yılı esaslı takvimler olması", aciklama: "İkisi de mali işler için Güneş yılı esaslıdır."}, 
        {soru: "Tarih öncesi çağları (Taş Devri, Maden Devri) araştıran bir tarihçi, aşağıdaki yardımcı bilimlerden hangisinden YARARLANAMAZ?", secenekler: ["A) Arkeoloji (Kazı Bilimi)", "B) Paleografya (Yazı Bilimi)", "C) Kimya (Karbon-14)", "D) Antropoloji (Irk Bilimi)", "E) Coğrafya"], cevap: "B) Paleografya (Yazı Bilimi)", aciklama: "Tarih öncesinde yazı yoktur."}, 
        {soru: "Dijital tarihçilikte 'veri güvenliği' neden önemli bir sorundur?", secenekler: ["A) Bilgisayarların pahalı olması", "B) Dijital verilerin siber saldırılarla değiştirilebilir, silinebilir veya manipüle edilebilir olması", "C) Tarihçilerin şifrelerini unutması", "D) İnternetin yavaş olması", "E) Kağıt kullanımının artması"], cevap: "B) Dijital verilerin siber saldırılarla değiştirilebilir, silinebilir veya manipüle edilebilir olması", aciklama: "Dijital veri manipüle edilebilir."}, 
        {soru: "Bir tarih araştırmasında kaynakların 'güvenilirliğinin' sorgulandığı, yazarın taraflı olup olmadığının incelendiği aşama hangisidir?", secenekler: ["A) Tarama", "B) Tasnif", "C) Tahlil", "D) Tenkit (Eleştiri)", "E) Terkip (Sentez)"], cevap: "D) Tenkit (Eleştiri)", aciklama: "Güvenilirlik sorgusu Tenkit aşamasıdır."}, 
        {soru: "'Öğretici Tarih' (Pragmatik Tarih) anlayışının temel amacı nedir?", secenekler: ["A) Sadece gerçekleri anlatmak", "B) Topluma ahlaki dersler vermek, milli duyguları güçlendirmek ve kahramanlıkları öne çıkarmak", "C) Olayları neden-sonuç ilişkisi içinde incelemek", "D) Efsaneleri tamamen reddetmek", "E) Kronolojik sıralama yapmak"], cevap: "B) Topluma ahlaki dersler vermek, milli duyguları güçlendirmek ve kahramanlıkları öne çıkarmak", aciklama: "Öğretici tarih fayda ve ders odaklıdır."}, 
        {soru: "Mısır hiyerogliflerini veya Göktürk kitabelerini okumak isteyen bir tarihçi, öncelikle hangi alanda uzmanlaşmalıdır?", secenekler: ["A) Paleografya ve Epigrafya", "B) Nümizmatik ve Kimya", "C) Coğrafya ve Arkeoloji", "D) Heraldik ve Sigillografya", "E) Etnografya ve İstatistik"], cevap: "A) Paleografya ve Epigrafya", aciklama: "Yazı ve kitabe bilimi gereklidir."}, 
        {soru: "Aşağıdakilerden hangisi dijitalleşmenin tarih araştırmalarına sağladığı 'demokratikleşme' etkisine örnektir?", secenekler: ["A) Sadece profesörlerin arşivlere girebilmesi", "B) Sıradan insanların da kendi aile arşivlerini, fotoğraflarını dijital platformlarda paylaşarak tarih yazımına veri sunabilmesi", "C) Devletin tüm belgeleri gizlemesi", "D) Tarih kitaplarının sadece üniversitelerde satılması", "E) İnternetin ücretli olması"], cevap: "B) Sıradan insanların da kendi aile arşivlerini, fotoğraflarını dijital platformlarda paylaşarak tarih yazımına veri sunabilmesi", aciklama: "Herkesin tarih yazımına katkısı demokratikleşmedir."}, 
        {soru: "'Kronoloji bilimi olmadan tarih kördür.' sözü neyi ifade eder?", secenekler: ["A) Tarihçilerin gözlük takması gerektiğini", "B) Olayların oluş sırası bilinmezse, neden-sonuç ilişkisinin kurulamayacağını ve olayın anlaşılamayacağını", "C) Tarihin bir sanat dalı olduğunu", "D) Zamanın önemsiz olduğunu", "E) Coğrafyanın daha önemli olduğunu"], cevap: "B) Olayların oluş sırası bilinmezse, neden-sonuç ilişkisinin kurulamayacağını ve olayın anlaşılamayacağını", aciklama: "Sıralama (kronoloji) olmadan neden-sonuç kurulamaz."}, 
        {soru: "Tarih araştırmalarında yapılan 'Anakronizm' (Tarih Yanılgısı) hatasına aşağıdakilerden hangisi örnektir?", secenekler: ["A) Fatih Sultan Mehmet'in portresini İtalyan ressama yaptırması", "B) Osmanlı Devleti'nde telefon hatlarının kurulduğunun iddia edilmesi (16. yüzyıl için)", "C) Sümerlerin Ziggurat yapması", "D) Mısırlıların Güneş takvimini bulması", "E) Türklerin atı evcilleştirmesi"], cevap: "B) Osmanlı Devleti'nde telefon hatlarının kurulduğunun iddia edilmesi (16. yüzyıl için)", aciklama: "16. yüzyılda telefon yoktur, bu anakronizmdir."}, 
        {soru: "Dijital Tarihçilikte, 'Born-digital' (Doğuştan dijital) kaynaklar ile 'Digitized' (Dijitalleştirilmiş) kaynaklar arasındaki temel fark nedir?", secenekler: ["A) Born-digital kaynakların kağıt formatının hiç olmaması, doğrudan dijital ortamda üretilmesi; diğerinin ise sonradan taranmasıdır.", "B) Born-digital kaynakların daha eski olmasıdır.", "C) Digitized kaynakların güvenilmez olmasıdır.", "D) Aralarında bir fark yoktur.", "E) Born-digital kaynakların sadece resim olmasıdır."], cevap: "A) Born-digital kaynakların kağıt formatının hiç olmaması, doğrudan dijital ortamda üretilmesi; diğerinin ise sonradan taranmasıdır.", aciklama: "Fark orijinalin kağıt olup olmamasıdır."}, 
        {soru: "Tarihsel bilginin üretim sürecinde 'Terkip' (Sentez) aşaması neden en yaratıcı aşama olarak kabul edilir?", secenekler: ["A) Çünkü tarihçi burada hayal gücünü kullanarak olayları uydurur.", "B) Çünkü tarihçi, topladığı ve doğruladığı dağınık bilgileri kendi bakış açısı ve yorumuyla birleştirerek yeni bir eser ortaya koyar.", "C) Çünkü bu aşamada kaynak kullanılmaz.", "D) Çünkü en kısa süren aşamadır.", "E) Çünkü sadece resimler birleştirilir."], cevap: "B) Çünkü tarihçi, topladığı ve doğruladığı dağınık bilgileri kendi bakış açısı ve yorumuyla birleştirerek yeni bir eser ortaya koyar.", aciklama: "Sentez, tarihçinin yorumunu kattığı inşadır."}, 
        {soru: "Halil İnalcık'ın 'Belgesiz tarih olmaz' ilkesi neyi zorunlu kılar?", secenekler: ["A) Olayların sadece kulaktan dolma bilgilerle yazılmasını", "B) Tarihçinin arşivlerde çalışarak birincil kaynaklara (ana kaynak) ulaşmasını", "C) Tarihin sadece siyasi olayları incelemesini", "D) Yabancı kaynakların reddedilmesini", "E) Ders kitaplarının tek kaynak olmasını"], cevap: "B) Tarihçinin arşivlerde çalışarak birincil kaynaklara (ana kaynak) ulaşmasını", aciklama: "Belge, bilimsel tarihin temelidir."}, 
        {soru: "Karbon-14 metodu neden her buluntuda kullanılamaz?", secenekler: ["A) Sadece metal eşyalarda kullanılabilmesi", "B) Sadece organik (bir zamanlar canlı olan: kemik, ahşap, kumaş) maddelerde kullanılabilmesi", "C) Sadece su altı buluntularında çalışması", "D) Çok ucuz olması", "E) 100 yıllık eşyaları ölçememesi"], cevap: "B) Sadece organik (bir zamanlar canlı olan: kemik, ahşap, kumaş) maddelerde kullanılabilmesi", aciklama: "C-14 sadece organik maddelerde çalışır."}, 
        {soru: "Bir tarihçinin 'Sigillografya' ve 'Heraldik' bilimlerinden yararlanması neyi aydınlatır?", secenekler: ["A) Halkın günlük yeme içme alışkanlıklarını", "B) Devletlerin resmi yazışma kurallarını, hükümdarlık sembollerini ve soyluluk ünvanlarını", "C) Coğrafi iklim şartlarını", "D) O dönemin müzik anlayışını", "E) Tarım aletlerinin yapısını"], cevap: "B) Devletlerin resmi yazışma kurallarını, hükümdarlık sembollerini ve soyluluk ünvanlarını", aciklama: "Mühür ve arma devlet sembolleridir."}, 
        {soru: "'Tarihsel Empati' yaparken düşülen tuzağa düşmeyen bakış açısı hangisidir?", secenekler: ["A) 'Kardeş katli yasası çok vahşice, Osmanlı yöneticileri katilmiş.' demek.", "B) 'O dönemde devletin parçalanmasını önlemek (Nizam-ı Alem) için, dönemin şartlarında bu uygulama zorunlu görülmüştür.' demek.", "C) 'Eski insanlar insan haklarını hiç bilmiyormuş.' diye yargılamak.", "D) 'Geçmişte yaşayanlar bizden daha zekiydi.' demek.", "E) Olayları görmezden gelmek."], cevap: "B) 'O dönemde devletin parçalanmasını önlemek (Nizam-ı Alem) için, dönemin şartlarında bu uygulama zorunlu görülmüştür.' demek.", aciklama: "Olayı kendi döneminin şartlarıyla değerlendirmek empatidir."}, 
        {soru: "Dijital beşeri bilimler kapsamında kullanılan 'Veri Madenciliği', tarihçiye neyi gösterir?", secenekler: ["A) Tek bir belgenin içeriğini", "B) Binlerce belge arasındaki gizli örüntüleri (pattern), örneğin yüzyıllar içindeki kelime kullanım sıklığının değişimini veya ticaret rotalarındaki yoğunluğu", "C) Belgelerin hangi kağıda yazıldığını", "D) Yazarın el yazısının güzelliğini", "E) Kitabın kapak rengini"], cevap: "B) Binlerce belge arasındaki gizli örüntüleri (pattern), örneğin yüzyıllar içindeki kelime kullanım sıklığının değişimini veya ticaret rotalarındaki yoğunluğu", aciklama: "Makro analiz ve örüntü keşfi sağlar."}, 
        {soru: "'Tarih, tarihçinin zihninde yeniden inşa edilir' görüşü neyi savunur?", secenekler: ["A) Geçmişin olduğu gibi, %100 objektif şekilde aktarılabileceğini", "B) Tarihin tamamen kurgusal bir roman olduğunu", "C) Geçmişin kendisi ile tarih kitabı arasındaki farkı; tarihçinin seçiciliğinin ve yorumunun kaçınılmaz olduğunu", "D) Tarihçilerin hafızasının çok güçlü olduğunu", "E) Tarihin bilim olmadığını"], cevap: "C) Geçmişin kendisi ile tarih kitabı arasındaki farkı; tarihçinin seçiciliğinin ve yorumunun kaçınılmaz olduğunu", aciklama: "Tarih, tarihçinin kurgusudur."}, 
        {soru: "Aşağıdaki yardımcı bilim eşleştirmelerinden hangisi YANLIŞTIR?", secenekler: ["A) Epigrafya - Kitabeler üzerindeki yazılar", "B) Antropoloji - İnsan ırklarının fiziksel özellikleri ve kültürleri", "C) Filoloji - Dillerin yapısı ve gelişimi", "D) Etnografya - Toplumların örf, adet ve kültürel eşyaları", "E) Paleografya - Eski paraların ekonomik değeri"], cevap: "E) Paleografya - Eski paraların ekonomik değeri", aciklama: "Paleografya yazı bilimidir, para bilimi Nümizmatiktir."}
    ]
};