// ==========================================
// 11. SINIF ÖĞRENCİ BEYAZ LİSTESİ (GÜVENLİK)
// ==========================================

const ADMIN_HESABI = { ad: "Murat Mutlu", no: "1453" };

const KAYITLI_OGRENCILER = [
    // 11-A Sınıfı
    { ad: "YUSUF ÇELİK", no: "2" },
    { ad: "ROJHAT ŞAHİN", no: "111" },
    { ad: "VEYSEL YILDIZHAN", no: "124" },
    { ad: "MÜŞERREF FİDAN", no: "126" },
    { ad: "İSMAİL EREN NAS", no: "128" },
    { ad: "MUHAMMET SAMİ TOPARLAK", no: "129" },
    { ad: "EYYÜP GÜNÜL", no: "131" },
    { ad: "EMİR BULUNTCİLAY", no: "134" },
    { ad: "BARIŞ OĞUZ", no: "135" },
    { ad: "ARDA ERGEN", no: "136" },
    { ad: "MUHAMMED NAYİF BİÇEN", no: "139" },
    { ad: "CUMA MUSTAFA", no: "141" },
    { ad: "GENCAY GÜNDÜZ", no: "142" },
    { ad: "FURKAN KAYRA", no: "143" },
    { ad: "MERVAN GÜNDÜZ", no: "145" },
    { ad: "HAMZA EKİNCİ", no: "149" },
    { ad: "SÜLEYMAN KURT", no: "150" },
    { ad: "VEYSEL OK", no: "163" },
    { ad: "ALİ CAN ÇELİK", no: "222" },
    { ad: "VEYSEL EREZ", no: "239" },
    { ad: "MUSA BOZKURT", no: "279" },
    { ad: "MEHMET NURİ SELÇİK", no: "282" },
    { ad: "EYÜP AYTAR", no: "288" },
    { ad: "SEVDA ÖZALP", no: "295" },
    { ad: "BARAN TÜRCAN", no: "616" },
    { ad: "ECE GELEN", no: "798" },
    { ad: "EYYÜP BERZAN ACET", no: "886" },
    { ad: "ONUR İNSEL", no: "2033" },
    { ad: "ARGES ALTUNKAYNAK", no: "857" },

    // 11-B Sınıfı
    { ad: "BİLAL ÇAKMAK", no: "116" },
    { ad: "BİRHAT ALİ TAYMUR", no: "155" },
    { ad: "AHMET İSLAM AYANA", no: "159" },
    { ad: "KADİR AK", no: "160" },
    { ad: "ÖMÜR BİLİR", no: "164" },
    { ad: "MEHMET EMİN KURT", no: "165" },
    { ad: "HARUN KAYRA", no: "173" },
    { ad: "BARAN ALİOĞLU", no: "177" },
    { ad: "YUSUF DEMİR", no: "181" },
    { ad: "HAMZA AK", no: "186" },
    { ad: "EMİRHAN FERHAT EZGİN", no: "188" },
    { ad: "MUHAMMED ALİ ÖZOĞUL", no: "198" },
    { ad: "İSA BERAT AY", no: "208" },
    { ad: "MUSTAFA ARDA ÇİFTÇİ", no: "214" },
    { ad: "UĞUR BERAT KAVAN", no: "215" },
    { ad: "HARUN DOĞAN ALTAN", no: "218" },
    { ad: "UMUTCAN YALÇIN", no: "219" },
    { ad: "YAKUP EYÜPCAN ÇİRAY", no: "220" },
    { ad: "ALİ ÇİFTÇİ", no: "224" },
    { ad: "ELİF GÜNCE", no: "263" },
    { ad: "BERAT ÜLEÇ", no: "290" },
    { ad: "BİLAL YİĞİT BEBER", no: "474" },
    { ad: "EMİR EFE TANRIVERDİ", no: "615" },
    { ad: "EMİNE BİLBEN", no: "2034" },
    { ad: "VEYSEL KESKİN", no: "2035" },
    { ad: "MEHMET EKİNCİ", no: "2036" },
    { ad: "MEHMET ALİ IŞIK", no: "2063" },

    // 11-C Sınıfı
    { ad: "HARUN TURAN", no: "148" },
    { ad: "FERHAT ÖZEN", no: "158" },
    { ad: "MUHAMMED SEFA AĞIN", no: "194" },
    { ad: "ELİF ALĞAN", no: "242" },
    { ad: "BURHAN YAŞAR", no: "248" },
    { ad: "ŞEYMA ŞUVAK", no: "251" },
    { ad: "BERRA SÖKMEN", no: "252" },
    { ad: "SEDAT EKİNCİ", no: "255" },
    { ad: "BERAT SÖKMEN", no: "267" },
    { ad: "YUNUS EMRE GARÇA", no: "273" },
    { ad: "ÖNDER BURAK GEZER", no: "276" },
    { ad: "CELAL ÖZER", no: "281" },
    { ad: "BİLAL ÇELİK", no: "287" },
    { ad: "EBUBEKİR SADIK TANIK", no: "298" },
    { ad: "VELAT IRMAK", no: "301" },
    { ad: "EMİR ALTUNER", no: "306" },
    { ad: "SENEM SALA", no: "313" },
    { ad: "EYYÜP AKSIN", no: "423" },
    { ad: "MEHMET AZAD CAN", no: "629" },
    { ad: "MUHAMMED VEYSEL SARIGOL", no: "641" },
    { ad: "İSMAİL MERT ERİPEK", no: "750" },
    { ad: "BERAT BADEM", no: "802" },
    { ad: "KADİR TİRKİ", no: "804" },
    { ad: "MEHMETCAN YALÇIN", no: "1011" },
    { ad: "YUSUF SEBUKTEKİN", no: "1012" },
    { ad: "YAKUP OĞUZ", no: "2023" },
    { ad: "MİRAÇ GÜNEŞ", no: "2038" },
    { ad: "AHMET ARİF BAYLAN", no: "2039" },
    { ad: "EMRE FURKAN CENGİZ", no: "2040" },

    // 11-D Sınıfı
    { ad: "GÖNÜL OĞUZ", no: "55" },
    { ad: "HAVIN İNANÇ", no: "104" },
    { ad: "ABDÜLSAMET ÖGE", no: "184" },
    { ad: "ABDURRAHİM TOKSOY", no: "193" },
    { ad: "RESUL ARSLAN", no: "203" },
    { ad: "MUHAMMED AKIN", no: "229" },
    { ad: "AHMET YASİN SIRLAN", no: "233" },
    { ad: "RAMAZAN OYGO", no: "235" },
    { ad: "MUHAMMED BEDİRHAN ÇİMEN", no: "250" },
    { ad: "SAMET ORÇUN KALKAN", no: "269" },
    { ad: "EMİR ENSAR KALKAN", no: "270" },
    { ad: "MEHMET YEKTA SEVİM", no: "286" },
    { ad: "HARUN TÜCER", no: "289" },
    { ad: "YASİN ERİK", no: "297" },
    { ad: "MEHMET ALİ UZLAN", no: "305" },
    { ad: "ABDÜLMELİK FIRAT EKİNCİ", no: "401" },
    { ad: "MUSTAFA GÜNEL", no: "407" },
    { ad: "EMİR CAN GÜNEL", no: "408" },
    { ad: "HARUN İNANÇ", no: "844" },
    { ad: "HÜSEYİN ÇELİK", no: "893" },
    { ad: "HARUN CEM İNANÇ", no: "2020" },
    { ad: "MURAT TAS", no: "2042" },
    { ad: "BİLAL SEVEN", no: "2043" },
    { ad: "YUNUS EMRE KOŞAR", no: "2044" },
    { ad: "BARAN ÜZÜMCÜ", no: "2045" },
    { ad: "MEKİ KURAL", no: "2046" },
    { ad: "HALİME BÜŞRA HAMİDİ", no: "2057" },
    { ad: "BİLAL CEM DİREK", no: "2064" },
    { ad: "MUHAMMED BURAK DEMİR", no: "2066" },

    // 11-E Sınıfı
    { ad: "ELANUR BELİKGİRAY", no: "52" },
    { ad: "FURKAN EVCİL", no: "132" },
    { ad: "HARUN KUM", no: "170" },
    { ad: "ÖZKAN DEMİR", no: "196" },
    { ad: "MUHAMMED YİĞİT ÖZTOPRAK", no: "204" },
    { ad: "ABDULLAH DİKENYOL", no: "205" },
    { ad: "EMRULLAH OYNAR", no: "212" },
    { ad: "ŞERVAN DEMİRTAŞ", no: "277" },
    { ad: "SELAHATTİN GÖKTAŞ", no: "284" },
    { ad: "ÖZGÜR YALAVUZ", no: "291" },
    { ad: "FIRAT TUNÇ", no: "310" },
    { ad: "VEYSEL ACET", no: "326" },
    { ad: "NURHAT KOÇ", no: "327" },
    { ad: "ÖMER BİLMEZ", no: "329" },
    { ad: "BARAN ESMER", no: "332" },
    { ad: "ECRİN RUŞA TANIK", no: "335" },
    { ad: "MEHMET ALİ GÜNEY", no: "337" },
    { ad: "EYYÜP GÖK", no: "355" },
    { ad: "EMİR EROL", no: "367" },
    { ad: "MAHSUM ERGİN", no: "381" },
    { ad: "ALİ ESAT EKİNCİ", no: "420" },
    { ad: "ENSAR EKMİŞ", no: "571" },
    { ad: "VEYSİ YILDIRIM", no: "607" },
    { ad: "UMUT SAÇİK", no: "669" },
    { ad: "NERGİZ ÇİLE", no: "757" },
    { ad: "FERMAN ETİĞ", no: "818" },
    { ad: "FATİH DURMAZ", no: "2047" },
    { ad: "HİRANUR KESKİN", no: "2048" },
    { ad: "ŞEFİK ZARİÇ", no: "2049" },
    { ad: "EMRE ÖRNEK", no: "2170" },

    // 11-F Sınıfı
    { ad: "BERK AYĞAN", no: "11" },
    { ad: "BERAT YORĞA", no: "154" },
    { ad: "DİYAR MENDEŞ", no: "199" },
    { ad: "SİPAN GÖKTAİ", no: "330" },
    { ad: "MEHMET EFETÜRK", no: "352" },
    { ad: "ZAL YILDIRIM", no: "356" },
    { ad: "HAYRUNNİSA BAŞÇI", no: "362" },
    { ad: "FIRAT BEDİRHAN KAYRA", no: "364" },
    { ad: "ÖZGÜR BOZKURT", no: "365" },
    { ad: "SERHAT YASAK", no: "378" },
    { ad: "MUHAMMED ENSAR İREN", no: "380" },
    { ad: "HÜSEYİN AYDEMİR", no: "385" },
    { ad: "HASİNE TOSUN", no: "392" },
    { ad: "ÖMER CİHANGİR", no: "395" },
    { ad: "JİNDANUR GÜNEŞ", no: "397" },
    { ad: "KEMAL SOYSAL", no: "465" },
    { ad: "MİR BEDİRHAN ALTUN", no: "475" },
    { ad: "AHMET YİĞİTTEKİN", no: "476" },
    { ad: "BEDİRHAN DEMİRTAŞ", no: "482" },
    { ad: "MERT DESTAN OYGO", no: "521" },
    { ad: "MUHAMMED MUSTAFA TALAY", no: "556" },
    { ad: "MUHAMMED AKGÜL", no: "579" },
    { ad: "YUSUF DEMİR", no: "747" },
    { ad: "ŞEYHMUS SEVEN", no: "794" },
    { ad: "MEVLÜT CAN GÖRNU", no: "2050" },
    { ad: "BİLAL ATAYAN", no: "2051" },
    { ad: "KEREM TAN", no: "2052" },
    { ad: "MİRAÇ ATAİBİŞ", no: "2053" },
    { ad: "AGIT DEĞİRMENCİ", no: "2054" },
    { ad: "MUHAMMED ALİ EMİNOĞLU", no: "2055" },

    // 11-G Sınıfı
    { ad: "MUHAMMED VEYSEL KAYRA", no: "12" },
    { ad: "ÖMER OKAY", no: "122" },
    { ad: "MUHAMMED EMİN YİĞİZ", no: "147" },
    { ad: "MAHMUT ÇETİN", no: "185" },
    { ad: "MUHAMMED MUSTAFA ARSLAN", no: "190" },
    { ad: "KEREM ÇİFTÇİ", no: "191" },
    { ad: "NUHHAT AYIŞ", no: "200" },
    { ad: "HARUN EMİN AKYOL", no: "236" },
    { ad: "BÜNYAMİN YUSUF ASTAN", no: "244" },
    { ad: "SUDENAZ ÇATI", no: "314" },
    { ad: "EYÜP CAN TAKA", no: "316" },
    { ad: "BARAN GÜNDÜZ", no: "322" },
    { ad: "ESRA ÖZCAN", no: "347" },
    { ad: "BİLAL MEMİŞ", no: "372" },
    { ad: "MEHMET ERDEM OCAK", no: "375" },
    { ad: "EGEMEN YEŞİLBAYRAK", no: "376" },
    { ad: "ABDULLAH YILDIZ", no: "389" },
    { ad: "YUSUFCAN SARI", no: "398" },
    { ad: "ENES SÜTCÜ", no: "404" },
    { ad: "UMUT VEYSEL EKİNGEN", no: "406" },
    { ad: "VEYSEL UGRAK", no: "419" },
    { ad: "AHMET ÇELİKKAYA", no: "931" },
    { ad: "MUHAMMED TEZEL", no: "2029" },
    { ad: "ESRA ENGİN", no: "2030" },
    { ad: "METIN ENGIN", no: "2031" },
    { ad: "HABİB BOZKURT", no: "2056" },
    { ad: "SEMRA ÇAĞİNE", no: "2058" },
    { ad: "ABDULLAH DİLEK", no: "2059" },
    { ad: "SALİH HALAVURT", no: "2061" },
    { ad: "MUHAMMED ARAFAT AYHAN", no: "2062" },
    { ad: "ZEKİ YELBOĞA", no: "2065" }
];