// ==========================================
// --- ÖĞRETMEN / MASTER GİRİŞİ ---
// ==========================================
const ADMIN_HESABI = { ad: "Murat Mutlu", no: "1310" };

// ==========================================
// --- 9. SINIF GÜVENLİK BEYAZ LİSTESİ (278 Öğrenci) ---
// ==========================================
const KAYITLI_OGRENCILER = [
    // --- 9-A ŞUBESİ ---
    { ad: "HANBEY BAKAN", no: "300" },
    { ad: "HASAN BAYHOCA", no: "302" },
    { ad: "ECE YAVUZ", no: "303" },
    { ad: "FERHAT SÜLEYMANOĞLU", no: "309" },
    { ad: "ÖMER CUMA SEVİPTEKİN", no: "312" },
    { ad: "LORIN KAYA", no: "317" },
    { ad: "HÜMEYRA BAL", no: "319" },
    { ad: "EMİRHAN DİLMAÇ", no: "320" },
    { ad: "HAMZA İPEK", no: "321" },
    { ad: "MUHAMMED GÖNEY", no: "325" },
    { ad: "MUHAMMED MUSTAFA BEKLEYİCİ", no: "334" },
    { ad: "YASİN ULUDAĞ", no: "340" },
    { ad: "AHMET BİLİK", no: "341" },
    { ad: "ABDULBAKİ BEĞDE", no: "343" },
    { ad: "ROJDA ÇELİK", no: "344" },
    { ad: "MEHMET ŞERİF AVCI", no: "345" },
    { ad: "ABDULLAH YUSUF ERENG", no: "346" },
    { ad: "HALİL EKİNCİ", no: "348" },
    { ad: "FURKAN CEMİLOĞLU", no: "350" },
    { ad: "BİLAL ÇELİK", no: "353" },
    { ad: "EMİR AYAZ ÖZEL", no: "358" },
    { ad: "MARYA ŞENGÜL", no: "360" },
    { ad: "MUSTAFA ÇOBAN", no: "371" },
    { ad: "İSMAİL İLGÜNER", no: "373" },
    { ad: "TAHA ORHAN", no: "374" },
    { ad: "KÜBRA DİNÇTAŞ", no: "384" },
    { ad: "ÖMER FARUK GÜNEŞ", no: "388" },
    { ad: "MUHAMMED ÇETİN", no: "399" },
    { ad: "MUHAMMED EMİR İPEK", no: "987" },
    { ad: "MUHAMMET ALİ FİLİZ", no: "1003" },

    // --- 9-B ŞUBESİ ---
    { ad: "SEDAT KARA", no: "94" },
    { ad: "MEHMET YUKUŞ", no: "96" },
    { ad: "ENES DAĞ", no: "103" },
    { ad: "ŞÜKRÜ ALTUNÇ", no: "238" },
    { ad: "YUSUF SEVİM", no: "403" },
    { ad: "MEHMET UFUK AKIL", no: "410" },
    { ad: "SERKAN DURMAZ", no: "411" },
    { ad: "BARAN ARSLAN", no: "412" },
    { ad: "MUHAMMED ENSAR SÖĞÜT", no: "415" },
    { ad: "MUSTAFA SAYHAN", no: "422" },
    { ad: "DEVRAN ŞEN", no: "446" },
    { ad: "MUHAMMED BARAN ONAT", no: "457" },
    { ad: "MEHMET BAŞAK", no: "480" },
    { ad: "ABDULLAH KANDEMİR", no: "483" },
    { ad: "HAMZA ÖZÇELİK", no: "496" },
    { ad: "SEFA SÖĞÜT", no: "498" },
    { ad: "RABIA SÖĞÜT", no: "501" },
    { ad: "MİRAÇ ÇALAR", no: "510" },
    { ad: "MUHAMMED ALİ TAYMUR", no: "545" },
    { ad: "ŞEHMUS YEŞİLMEN", no: "549" },
    { ad: "YUNUS İŞÇİMEN", no: "576" },
    { ad: "MUSTAFA KARDAŞ", no: "577" },
    { ad: "MERVE ESMA HATUN EVCİL", no: "590" },
    { ad: "MUHAMED MUSTAFA İDE", no: "596" },
    { ad: "NEVROZ ORAK", no: "606" },
    { ad: "ZİLA NUR KUTLU", no: "628" },
    { ad: "MUHAMMED MUSTAFA ŞEN", no: "642" },
    { ad: "SERHAT ESİRTİ", no: "650" },
    { ad: "SADUN EMRE BARLAK", no: "932" },
    { ad: "MURAT ARAS TUNÇ", no: "954" },

    // --- 9-C ŞUBESİ ---
    { ad: "YÜCEL KIZILKAYA", no: "18" },
    { ad: "YUSUF İSLAM TÜZÜN", no: "66" },
    { ad: "EREN ESRUĞİN", no: "243" },
    { ad: "SEMİH USLU", no: "342" },
    { ad: "FATMA NUR KÖLGE", no: "426" },
    { ad: "MELEK KÖLGE", no: "450" },
    { ad: "BİLAL KAYA", no: "553" },
    { ad: "MUHAMMED SEMİH GÜNDEM", no: "564" },
    { ad: "BAGER KARDAŞ", no: "575" },
    { ad: "YUNUS EMRE ÖKSÜZ", no: "602" },
    { ad: "MUHAMMED YASİN YARDIM", no: "648" },
    { ad: "MUHAMMED SAFA ASLAN", no: "703" },
    { ad: "CEYLİN NUR GÜREL", no: "724" },
    { ad: "MEHMED ALİ MUTLU", no: "746" },
    { ad: "CEMİLE BULUT", no: "762" },
    { ad: "HAVIN NUR ADLIĞ", no: "763" },
    { ad: "BİLAL SEVİM", no: "848" },
    { ad: "YUSUF TEKİN", no: "863" },
    { ad: "BİLAL YALKIN ULUSOY", no: "868" },
    { ad: "ERSİN ŞAHİN", no: "901" },
    { ad: "ÇINAR DİLEK", no: "910" },
    { ad: "BÜNYAMİN ÖNCÜ", no: "927" },
    { ad: "YUSUF ÖNCÜ", no: "928" },
    { ad: "MERT BEDRAN CAMCIER", no: "957" },
    { ad: "HATİCE YILDIZ", no: "959" },
    { ad: "HÜSEYİN YETİŞ", no: "960" },
    { ad: "MUHAMMED YUSUF AYDIN", no: "964" },
    { ad: "MUHAMMED MUSTAFA AFŞİN", no: "970" },
    { ad: "AHMET ÖZGÜR NAS", no: "993" },

    // --- 9-D ŞUBESİ ---
    { ad: "EMİR EYMEN KORKMAZ", no: "41" },
    { ad: "MUSTAFA MİRAÇ SAYDUN", no: "107" },
    { ad: "MERVE DURMAZ", no: "246" },
    { ad: "YUSUF BAZ", no: "254" },
    { ad: "ZELAL BAŞKAN", no: "257" },
    { ad: "VEYSEL EPEKİNCİ", no: "258" },
    { ad: "ELİF YEŞİM DİLEGİL", no: "262" },
    { ad: "ÖMER ARDA DEMİR", no: "359" },
    { ad: "EMİRHAN AY", no: "405" },
    { ad: "NUH ZANYAR AKSOY", no: "434" },
    { ad: "KEMAL ASLAN", no: "437" },
    { ad: "MEHMET ADEM GİDİCİ", no: "443" },
    { ad: "YUSUF ENİS ARTIK", no: "451" },
    { ad: "SAMED EKDİ", no: "566" },
    { ad: "HASAN ΤΟΥ", no: "572" },
    { ad: "MUHAMMED ALİ ELMUHAMMED", no: "581" },
    { ad: "ASMİN SINCAR", no: "624" },
    { ad: "DİCLE ÇELİK", no: "625" },
    { ad: "EMİR LADİN ÖZALP", no: "633" },
    { ad: "MEHMET ALİ ALİOĞLU", no: "635" },
    { ad: "MUHAMMED SEFA TEMEL", no: "643" },
    { ad: "İSHAK BAKIŞ", no: "780" },
    { ad: "NUDEM TÜRKOĞLU", no: "786" },
    { ad: "AHMET YILDIZ", no: "788" },
    { ad: "HAMZA BÜYÜKKAL", no: "950" },
    { ad: "TUANA IŞIK", no: "953" },
    { ad: "SALİH ZEBİH TUNÇ", no: "976" },
    { ad: "İBRAHİM ÖZDEMİR", no: "992" },
    { ad: "YUSUF ALVER", no: "998" },
    { ad: "BİLAL TİRKİ", no: "999" },

    // --- 9-E ŞUBESİ ---
    { ad: "YUSUF OĞUZ", no: "59" },
    { ad: "ABDULCELİL EZER", no: "105" },
    { ad: "ASMİN TEKİN", no: "110" },
    { ad: "MUHAMMED ASLAN", no: "241" },
    { ad: "ŞEVKET BAŞAK", no: "529" },
    { ad: "MUHAMMED MUSTAFA ÇELİK", no: "619" },
    { ad: "UMUTCAN ORAK", no: "634" },
    { ad: "SEHER BAYRAM", no: "660" },
    { ad: "BARIŞ ERENG", no: "661" },
    { ad: "VEYSEL EMİR ADAK", no: "662" },
    { ad: "YUSUF TİTİZ", no: "680" },
    { ad: "YAĞMUR TEKİN", no: "700" },
    { ad: "YİĞİT EFE GÜZEL", no: "708" },
    { ad: "EFE TEKİN", no: "711" },
    { ad: "EDANUR SİRAY", no: "712" },
    { ad: "BERAT IŞIK", no: "713" },
    { ad: "YUNUS DURSUN", no: "714" },
    { ad: "YAĞMUR AKIN", no: "726" },
    { ad: "UMUT AKIN", no: "728" },
    { ad: "MUHAMMED ALİ SEZGİN", no: "730" },
    { ad: "AGİT SEZGİN", no: "732" },
    { ad: "MUHAMMED AYDOĞAN", no: "734" },
    { ad: "MALİK KOYUN", no: "754" },
    { ad: "HAMZA ÖLMEZ", no: "759" },
    { ad: "MUHAMMED MUSTAFA ABLAK", no: "774" },
    { ad: "BATIN ELİBOL", no: "978" },
    { ad: "MUSTAFA KAYRA", no: "979" },
    { ad: "MUHAMMED YILDIRIM", no: "981" },
    { ad: "MUHAMMED YUSUF BULUT", no: "983" },
    { ad: "MUHAMMED SEFA GÜNDÜZ", no: "2069" },

    // --- 9-F ŞUBESİ ---
    { ad: "BÜNYAMİN TURAN", no: "167" },
    { ad: "ECRİN KAPLAN", no: "499" },
    { ad: "MİRAN ARSLAN", no: "528" },
    { ad: "EMİRHAN ARSLAN", no: "636" },
    { ad: "HÜSEYİN MİRAÇ ÇILGIN", no: "686" },
    { ad: "ÖMER ASAF ASLAN", no: "852" },
    { ad: "MUHAMMED BİLİK", no: "868" },
    { ad: "HAKAN HAMARAT", no: "872" },
    { ad: "RUKEN AKDAŞ", no: "878" },
    { ad: "MEDINE AKDAŞ", no: "879" },
    { ad: "MUHAMMED YASİN AKDAŞ", no: "881" },
    { ad: "DENİZ AKYÜZ", no: "882" },
    { ad: "MUSTAFA AVCI", no: "884" },
    { ad: "YUSUF ÇINAR", no: "888" },
    { ad: "YUSUF YILMAZ", no: "889" },
    { ad: "İREM ÖNCÜ", no: "891" },
    { ad: "SERHAT ÖNCÜ", no: "892" },
    { ad: "ECRİN AKDAŞ", no: "897" },
    { ad: "MUHAMMED MUSTAFA GÜNEŞ", no: "898" },
    { ad: "MEHMET ALİ TAZ", no: "899" },
    { ad: "ABDURRAHΜΑΝ UÇAR", no: "903" },
    { ad: "OMER GÖKDEMİR", no: "905" },
    { ad: "İBRAHİM EDHEM SEVİM", no: "907" },
    { ad: "HASAN TARHAN", no: "911" },
    { ad: "TUANA KONAK", no: "925" },
    { ad: "ÖMER UĞRAK", no: "949" },
    { ad: "FIRAT FURAN", no: "950" },
    { ad: "MUHAMMED SEFA UĞRAK", no: "952" },
    { ad: "BARIŞ ÜLKER", no: "956" },
    { ad: "AGİT AKIN", no: "967" },

    // --- 9-G ŞUBESİ ---
    { ad: "ABDULLAH ERİPEK", no: "5" },
    { ad: "MUHAMMED BULKUT", no: "70" },
    { ad: "SERHAT YILDIZ", no: "73" },
    { ad: "ABDULLAH AYDIN", no: "74" },
    { ad: "YAKUP DAĞ", no: "75" },
    { ad: "LEVEND ABDULLAH", no: "76" },
    { ad: "YUSUF KOŞAR", no: "87" },
    { ad: "CANER ZENGİN", no: "91" },
    { ad: "EREN YALÇIN", no: "102" },
    { ad: "UMUT SEVİM", no: "151" },
    { ad: "YUSUF FERZAD GÖL", no: "232" },
    { ad: "İSA ARSLAN", no: "436" },
    { ad: "İBRAHİM İDİĞ", no: "467" },
    { ad: "TUANA GÜNDEM", no: "621" },
    { ad: "CESUR DENİZ", no: "637" },
    { ad: "YUNUS SAVCI", no: "705" },
    { ad: "KEVSER BALİ", no: "725" },
    { ad: "ŞAHİN SAVAŞ", no: "778" },
    { ad: "MUHAMMED SAÏT İMRAN OKAN", no: "851" },
    { ad: "MİRZE KONAK", no: "867" },
    { ad: "HASAN SAYIŞ", no: "965" },
    { ad: "ALICAN BİLAYAK", no: "966" },
    { ad: "MUSTAFA SÖNMEZSOY", no: "968" },
    { ad: "MUHAMMED FURKAN KAYA", no: "969" },
    { ad: "MESUT EKE", no: "971" },
    { ad: "MUHAMMED KERİM AYTEMUR", no: "974" },
    { ad: "MUHAMMED ALİ GÖKMEN", no: "977" },
    { ad: "İHSAN ULUTAŞ", no: "1001" },
    { ad: "MUSTAFA ENSAR DEMİRTAŞ", no: "1030" },
    { ad: "ÖZGÜR DEMİR", no: "2118" },

    // --- 9-H ŞUBESİ ---
    { ad: "ENSAR GÖNÜLAÇAR", no: "175" },
    { ad: "EBUBEKİR TAYMUR", no: "178" },
    { ad: "BİLAL TULAY", no: "810" },
    { ad: "NAFİYE ESRA İNANÇ", no: "876" },
    { ad: "İREM İRGİ", no: "908" },
    { ad: "YASİN ÇAKAR", no: "912" },
    { ad: "AYET KERİM ASLAN", no: "913" },
    { ad: "YUSUF YİĞİZ", no: "914" },
    { ad: "EYLÜL EYMEN AKSOY", no: "917" },
    { ad: "ZÜBEYİR SEVİM", no: "918" },
    { ad: "MUHAMMET EFE ÇELİK", no: "920" },
    { ad: "BÜNYAMİN YILMAZ", no: "921" },
    { ad: "BERFİN ÇELİK", no: "922" },
    { ad: "ABDULSAMET SEVİK", no: "924" },
    { ad: "AHMET YASİN ARTIK", no: "926" },
    { ad: "ARDIL ERİPEK", no: "930" },
    { ad: "EMİRHAN TAŞ", no: "934" },
    { ad: "MUHAMMED POLAT", no: "935" },
    { ad: "MUHAMMED YUSUF BOZAN", no: "936" },
    { ad: "MUHAMMED MERT DİREK", no: "937" },
    { ad: "BARIŞ TEMEL", no: "938" },
    { ad: "BÜNYAMİN AKBIYIK", no: "939" },
    { ad: "HARUN AKBIYIK", no: "940" },
    { ad: "MEHMET SALIH ÖZBEK", no: "943" },
    { ad: "AHMET EREN", no: "944" },
    { ad: "ENSAR İLENÇ", no: "945" },
    { ad: "BOTAN BATUR", no: "946" },
    { ad: "AYSEL AYIS", no: "947" },
    { ad: "ELİF SU DAĞ", no: "955" },
    { ad: "MUHAMMED BERAT TUNÇ", no: "961" },

    // --- 9-İ ŞUBESİ ---
    { ad: "BERKAY NAZMİ BALIK", no: "9" },
    { ad: "MUHAMMED CAN BOZAN", no: "14" },
    { ad: "YUSUF ÇETİN", no: "15" },
    { ad: "ENES SÖNMEZSOY", no: "20" },
    { ad: "ÜVEYS AKDAĞ", no: "22" },
    { ad: "MUHAMMED MUSTAFA TÜZÜN", no: "27" },
    { ad: "NECMETTİN SEZGİN", no: "28" },
    { ad: "MAHSUM ZİNDAN YILMAZ", no: "32" },
    { ad: "HAMZA YILMAZ", no: "35" },
    { ad: "SİPAN BATIN", no: "39" },
    { ad: "MUHAMMET EYÜP CENGİZ", no: "42" },
    { ad: "SERHAT USLU", no: "45" },
    { ad: "YASİN YUSUF YILMAZ", no: "46" },
    { ad: "MUHAMMED ALI ENSAR FIRAT", no: "417" },
    { ad: "İBRAHİM OĞUZ", no: "709" },
    { ad: "BARAN ALİ UÇUN", no: "781" },
    { ad: "MUSTAFA CANGİR", no: "789" },
    { ad: "İSHAK YILDIZ", no: "841" },
    { ad: "MUSHAP MUTLU", no: "862" },
    { ad: "MUSAB ALIN", no: "864" },
    { ad: "SÜLEYMAN ÇAKAR", no: "871" },
    { ad: "ASENAT GÜNDEM", no: "877" },
    { ad: "YAĞMUR İNAĞ", no: "890" },
    { ad: "TUNA AVCI", no: "900" },
    { ad: "MELEK NAZ DEMİR", no: "904" },
    { ad: "RUKEN DEMİR", no: "919" },
    { ad: "MUHAMMED ÖZCAN", no: "958" },
    { ad: "ABDULSAMET ÇETİN", no: "962" },
    { ad: "ARDA MÜJDECİ", no: "982" },
    { ad: "BARAN ÇATI", no: "2068" },

    // --- 9-J ŞUBESİ ---
    { ad: "TUBA ERKOYUNCU", no: "56" },
    { ad: "BİLAL DEMİR", no: "60" },
    { ad: "MUHAMMED MEMİŞ", no: "62" },
    { ad: "BERKAN ADANUR", no: "64" },
    { ad: "FADIL ADANUR", no: "65" },
    { ad: "MİRAN EYMEN ALP", no: "66" },
    { ad: "HAYRUNNİSA AK", no: "67" },
    { ad: "ENES TAŞKIN", no: "68" },
    { ad: "RECEP KAVAK", no: "72" },
    { ad: "AHMET BEKİL", no: "97" },
    { ad: "HAMZA ÖNEN", no: "130" },
    { ad: "CEMRE KANTAR", no: "162" },
    { ad: "KENDAL YILDIRIM", no: "172" },
    { ad: "HARUN IŞIK", no: "187" },
    { ad: "İBRAHİM BAZ", no: "192" },
    { ad: "YUSUF ŞAHİN", no: "197" },
    { ad: "FIRAT ÇİÇEK", no: "210" },
    { ad: "HÜSEYİN GÜLMÜŞ", no: "225" },
    { ad: "HASAN GÜLMÜŞ", no: "228" },
    { ad: "ELİF İŞÇİMEN", no: "256" },
    { ad: "YUSUF YIKILMAZ", no: "531" },
    { ad: "HEVİN KARTAL", no: "664" },
    { ad: "EZEL BOZKURT", no: "809" },
    { ad: "MUHAMMED ENES KERSE", no: "860" },
    { ad: "MUHAMMED TAHA SEVİNÇ", no: "865" },
    { ad: "VEYSEL UMUT SEVEN", no: "984" },
    { ad: "ASMİN GÜNEŞ", no: "985" },
    { ad: "ÖZCAN EKMEN", no: "990" },
    { ad: "DEVRİM GÜNEŞ", no: "991" },
    { ad: "HASİNE KANTAR", no: "997" },

    // --- 9-K ŞUBESİ ---
    { ad: "EJDER KONAK", no: "479" },
    { ad: "MUHAMMED ALİ AKKAYA", no: "806" },
    { ad: "HALID BAĞDU", no: "826" },
    { ad: "HEVAL KILIÇ", no: "839" },
    { ad: "BARAN ŞAHİN", no: "2103" },
    { ad: "MEHMET ŞAH EKİNCİ", no: "2114" },
    { ad: "SULTAN ÜNLİ", no: "2121" },
    { ad: "YUSUF MİRHAT DURSUN", no: "2127" },
    { ad: "ZELAL YILMAZ", no: "2128" }
];