// ==========================================
// 12. SINIF ÖĞRENCİ BEYAZ LİSTESİ (GÜVENLİK)
// ==========================================

const ADMIN_HESABI = { ad: "Murat Mutlu", no: "1453" };

const KAYITLI_OGRENCILER = [
    // 12-A Sınıfı
    { ad: "FATİH ARSLAN", no: "21" },
    { ad: "FIRAT KAVŞUT", no: "169" },
    { ad: "SALİH GÜMÜŞ", no: "211" },
    { ad: "OSMAN YALÇIN", no: "245" },
    { ad: "AHMET TAVUKÇU", no: "259" },
    { ad: "BERAT ŞİMŞEK", no: "315" },
    { ad: "BAYRAM YEL", no: "328" },
    { ad: "MİRAÇ ERTOĞUM", no: "331" },
    { ad: "HÜSEYİN SOYSAL", no: "338" },
    { ad: "SAMET DEMİR", no: "383" },
    { ad: "ÖMER FARUK NİGAR", no: "393" },
    { ad: "OMER TURUT", no: "396" },
    { ad: "MUHAMMED EMİN BİÇEN", no: "400" },
    { ad: "YUNUS EMRE TUNÇ", no: "414" },
    { ad: "CAN TAŞKIN", no: "429" },
    { ad: "VEYSEL BUĞU", no: "464" },
    { ad: "YUNUS EMRE ONUR", no: "505" },
    { ad: "SEDAT AYAZ", no: "586" },
    { ad: "YUSUF YILDIZ", no: "644" },
    { ad: "BERAAT AKSOY", no: "670" },
    { ad: "ABDÜLSAMET GÜVERÇİN", no: "679" },
    { ad: "ÖZCAN AKIN", no: "1086" },
    { ad: "ÜMRAN BEBER", no: "1099" },
    { ad: "FATIH SEZGİN", no: "1125" },
    { ad: "MUHAMMED MUSTAFA ZEYDANLI YILDIZ", no: "2000" },
    { ad: "BEKİR YUSUF AYYILDIZ", no: "2001" },
    { ad: "FERIT ÖZLÜK", no: "2002" },
    { ad: "MUHAMMED EZGİN", no: "2003" },
    { ad: "İBRAHİM HALİL BİLGİ", no: "2004" },
    { ad: "HASİBE EKREMOĞLU", no: "2332" },
    { ad: "HATİCE EKREMOĞLU", no: "2333" },

    // 12-C Sınıfı
    { ad: "SUADA AKYÜZ", no: "171" },
    { ad: "UMUT TOĞUÇ", no: "182" },
    { ad: "MEHMET YUSUF ALIOĞLU", no: "266" },
    { ad: "UMUT KAÇAR", no: "433" },
    { ad: "HÜSEYİN MALİK TOY", no: "440" },
    { ad: "BİLAL KAÇMAZ", no: "454" },
    { ad: "BEYZA NUR ERKEK", no: "456" },
    { ad: "HAMZA EZGİN", no: "468" },
    { ad: "ENES EZGİN", no: "472" },
    { ad: "MAHİR ARITÜRK", no: "477" },
    { ad: "MUSTAFA KANAT", no: "488" },
    { ad: "FARUK BALCI", no: "492" },
    { ad: "MUHAMMED SAMİ ARAY", no: "495" },
    { ad: "MUHAMMED VEYSEL YILMAZ", no: "502" },
    { ad: "RUMET YILMAZ", no: "503" },
    { ad: "ARDA ÇETİN", no: "522" },
    { ad: "BEYZANUR ÇELİK", no: "593" },
    { ad: "YUSUF BİLAL YURDEM", no: "689" },
    { ad: "MUHARREM SAMED DÜNDAR", no: "698" },
    { ad: "EMİRHAN TAŞ", no: "749" },
    { ad: "MİKAİL ASI", no: "988" },
    { ad: "MEHMET SALİH AKBAY", no: "1080" },
    { ad: "MELEKNUR BAĞAÇ", no: "1096" },
    { ad: "SİPAN ÇINAR", no: "1098" },
    { ad: "AHMET MAMİŞ", no: "1146" },
    { ad: "HIRANUR TİRKİ", no: "2008" },
    { ad: "ÇEKDAR ÖZER", no: "2009" },
    { ad: "EMRE ONAL", no: "2010" },
    { ad: "İHSAN MEHMETOĞLU", no: "2027" },
    { ad: "BAVER TETER", no: "2131" },

    // 12-D Sınıfı
    { ad: "DİCLE DOĞAN", no: "23" },
    { ad: "EMİN ÇİFTÇİ", no: "88" },
    { ad: "FATİH TAŞ", no: "202" },
    { ad: "ROJİN KESKİN", no: "253" },
    { ad: "BERAT TURAL", no: "260" },
    { ad: "YUNUS EMRE EROĞLU", no: "261" },
    { ad: "ENES TAYMUR", no: "263" },
    { ad: "TAHA YASİN AKINCI", no: "354" },
    { ad: "FURKAN ALP", no: "369" },
    { ad: "ELANUR TEZEL", no: "379" },
    { ad: "ZEYNEP ŞEN", no: "386" },
    { ad: "BEHCET ADSAN", no: "394" },
    { ad: "YAKUP ÖZTÜRK", no: "489" },
    { ad: "MEHMET AKİF AY", no: "520" },
    { ad: "ÖMER ELADLİ", no: "584" },
    { ad: "HÜSNÜ KEREM TUNÇ", no: "609" },
    { ad: "EYÜP ATIC", no: "640" },
    { ad: "MUHAMMED ACAR", no: "678" },
    { ad: "NISA NUR YILMAZ", no: "710" },
    { ad: "SAMİR YUSUF YILMAZ", no: "800" },
    { ad: "MURAT BULUT", no: "869" },
    { ad: "CANER DEGİRMENCİOĞLU", no: "885" },
    { ad: "ADNAN ALİ KESKİN", no: "894" },
    { ad: "BÜNYAMİN BERKEN GÖL", no: "933" },
    { ad: "ESMANUR ADIYAMAN", no: "986" },
    { ad: "ABDULLAH SEVGİLİ", no: "1072" },
    { ad: "OSMAN GÜNES", no: "1102" },
    { ad: "MUHAMMED EMİR TOĞ", no: "2012" },
    { ad: "MEVLÜT HALAVURT", no: "2014" },
    { ad: "HAMZA CAN EKİNCİ", no: "2015" },
    { ad: "MUHAMMET ÖMER SAKIK", no: "2016" },

    // 12-E Sınıfı
    { ad: "GÜLFEM ÇİLE", no: "57" },
    { ad: "ENES ÖZCAN", no: "119" },
    { ad: "ÖMÜRCAN GÜÇLÜ", no: "216" },
    { ad: "ENES ÖZBEK", no: "223" },
    { ad: "MUSTAFA SEZGİN", no: "500" },
    { ad: "SAMED ÖZTÜRK", no: "507" },
    { ad: "İBRAHİM HALİL MUTLU", no: "509" },
    { ad: "ENES ATAK", no: "567" },
    { ad: "SERDAL TAŞ", no: "573" },
    { ad: "HALİL ALKIŞ", no: "589" },
    { ad: "İSMAİL SAYIŞ", no: "597" },
    { ad: "MUSTAFA KAAN POLAT", no: "601" },
    { ad: "FARUK YILMAZ", no: "617" },
    { ad: "BAHOZ YILMAZ", no: "626" },
    { ad: "VEYSEL MUŞLUOĞLU", no: "629" },
    { ad: "AHMET KARDAŞ", no: "630" },
    { ad: "DILJİN DOĞANAY", no: "646" },
    { ad: "MUHAMMED GEYLANİ SARIGÖL", no: "649" },
    { ad: "ALİ ŞEHMUS CAN", no: "653" },
    { ad: "MUHAMMED KADİR ULUDAĞ", no: "655" },
    { ad: "İBRAHİM AVCI", no: "657" },
    { ad: "ASEMİN ERBAŞ", no: "663" },
    { ad: "ÖZGÜR İPEK", no: "666" },
    { ad: "HÜSEYİN KARDAŞ", no: "2013" },
    { ad: "GÖKHAN ARSLAN", no: "2017" },
    { ad: "MAHMUT ÇİFTÇİ", no: "2018" },
    { ad: "SEMİH ESRUĞİN", no: "2019" },
    { ad: "MUSTAFA ŞEVDER BEĞDE", no: "2022" },
    { ad: "RECEP SUNAR", no: "2024" },
    { ad: "RÜSTEM SEYHAN", no: "2026" },

    // 12-F Sınıfı
    { ad: "KADİRCAN TEZEL", no: "82" },
    { ad: "HARUN OĞUZ", no: "121" },
    { ad: "ORHAN KARDAŞ", no: "357" },
    { ad: "BİLAL KONAK", no: "390" },
    { ad: "ALİ YAHYA DEMİRDAĞ", no: "455" },
    { ad: "VEYSEL ÖZDİL", no: "511" },
    { ad: "MUHAMMED KAYA", no: "512" },
    { ad: "MUHAMMED NURSİN YILDIRIM", no: "530" },
    { ad: "İLKNUR BARAN", no: "550" },
    { ad: "MUSTAFA AKSOY", no: "618" },
    { ad: "MUSTAFA EKİNCİ", no: "622" },
    { ad: "MUHAMMED MUSTAFA AYHAN", no: "623" },
    { ad: "HALİL YILDIRIM", no: "665" },
    { ad: "BARAN KAYA", no: "681" },
    { ad: "İLYAS KAYA", no: "707" },
    { ad: "SALİH SİNCAR", no: "772" },
    { ad: "MUHAMMED ZİLAN ÖZDİL", no: "785" },
    { ad: "MURAT TOPRAK", no: "858" },
    { ad: "MUHAMMED YUSUF KAYRA", no: "883" },
    { ad: "FURKAN ULUÇ", no: "975" },
    { ad: "ENES AYDIN", no: "1037" },
    { ad: "HASAN SEVİM", no: "1051" },
    { ad: "KADER ÖZALP", no: "1074" },
    { ad: "UMUT SIRAY", no: "1116" },
    { ad: "ŞEVİN GİRTİ", no: "1118" },
    { ad: "MURAT AY", no: "1127" },
    { ad: "BERAT DUMAN", no: "2005" },
    { ad: "MEHMET YUSUF AYHAN", no: "2006" },
    { ad: "YASİN YELBOĞA", no: "2011" },
    { ad: "MEHMET KİRACI", no: "2028" },

    // ÖATP 12-A Sınıfı
    { ad: "MUHAMMED ESAT DİNÇ", no: "3" }
];